package panelcontract

import (
	"bytes"
	"fmt"
	"reflect"
	"sort"
	"strings"

	"github.com/smykla-skalski/smyklot/internal/orgsync/filemerge"
	"github.com/smykla-skalski/smyklot/pkg/config"
)

const (
	// FrontendFile is the generated browser-side render contract.
	FrontendFile = "internal/panel/frontend/src/lib/sync-file-render.generated.ts"
	generatedDoc = "// Code generated by internal/panelcontract. DO NOT EDIT."
)

var namedTypes = map[reflect.Type]string{
	reflect.TypeFor[config.Source]():            "ConfigSource",
	reflect.TypeFor[LayerState]():               "FormattingLayerState",
	reflect.TypeFor[config.FormattingPatch]():   "FormattingPatch",
	reflect.TypeFor[config.FormattingPolicy]():  "FormattingPolicy",
	reflect.TypeFor[config.FormattingSources](): "FormattingSources<ConfigSource>",
	reflect.TypeFor[filemerge.Spec]():           "Omit<SyncFileMerge, 'path'>",
}

// RenderTypeScript derives the public interfaces from the Go DTOs, then adds
// strict parsers for the two untrusted JSON boundaries that use them.
func RenderTypeScript() ([]byte, error) {
	var output bytes.Buffer
	output.WriteString(generatedDoc)
	output.WriteString("\n\nimport {\n  parseFormattingPatch,\n  parseFormattingPolicy,\n  parseFormattingSources,\n  type FormattingPatch,\n  type FormattingPolicy,\n  type FormattingSources,\n} from './formatting';\n")
	output.WriteString("import type { SyncFileMerge } from './types';\n\n")
	writeUnion(&output, "ConfigSource", sourceStrings(ConfigSources()))
	writeUnion(&output, "FormattingLayerState", stateStrings(LayerStates()))

	for _, value := range []any{
		SyncFileRenderInput{},
		SyncFileRenderRepositoryInput{},
		SyncFileRenderDiagnostic{},
		SyncFileFormattingLayer{},
		SyncFileFormattingResolution{},
		SyncFileRenderResponse{},
	} {
		if err := writeInterface(&output, reflect.TypeOf(value)); err != nil {
			return nil, err
		}
	}

	output.WriteString(parserSource)

	return output.Bytes(), nil
}

func writeUnion(output *bytes.Buffer, name string, values []string) {
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = fmt.Sprintf("'%s'", value)
	}
	declaration := fmt.Sprintf("export type %s = %s;", name, strings.Join(quoted, " | "))
	if len(declaration) > 100 {
		fmt.Fprintf(output, "export type %s =\n  %s;\n\n", name, strings.Join(quoted, " | "))

		return
	}
	fmt.Fprintf(output, "%s\n\n", declaration)
}

func writeInterface(output *bytes.Buffer, shape reflect.Type) error {
	fmt.Fprintf(output, "export interface %s {\n", shape.Name())
	for index := range shape.NumField() {
		field := shape.Field(index)
		name, optional := jsonName(field)
		if name == "" {
			continue
		}
		typeName, err := typeScriptType(field.Type)
		if err != nil {
			return fmt.Errorf("%s.%s: %w", shape.Name(), field.Name, err)
		}
		if field.Type.Kind() == reflect.Pointer {
			optional = true
		}
		mark := ""
		if optional {
			mark = "?"
		}
		fmt.Fprintf(output, "  %s%s: %s;\n", name, mark, typeName)
	}
	output.WriteString("}\n\n")

	return nil
}

func typeScriptType(shape reflect.Type) (string, error) {
	if shape.Kind() == reflect.Pointer {
		shape = shape.Elem()
	}
	if name, ok := namedTypes[shape]; ok {
		return name, nil
	}
	switch shape.Kind() {
	case reflect.String:
		return "string", nil
	case reflect.Bool:
		return "boolean", nil
	case reflect.Slice:
		item, err := typeScriptType(shape.Elem())
		if err != nil {
			return "", err
		}
		return item + "[]", nil
	case reflect.Struct:
		return shape.Name(), nil
	default:
		return "", fmt.Errorf("unsupported Go type %s", shape)
	}
}

func jsonName(field reflect.StructField) (string, bool) {
	parts := strings.Split(field.Tag.Get("json"), ",")
	if len(parts) == 0 || parts[0] == "-" {
		return "", false
	}
	return parts[0], len(parts) > 1 && parts[1] == "omitempty"
}

func sourceStrings(values []config.Source) []string {
	result := make([]string, len(values))
	for index, value := range values {
		result[index] = string(value)
	}
	return result
}

func stateStrings(values []LayerState) []string {
	result := make([]string, len(values))
	for index, value := range values {
		result[index] = string(value)
	}
	return result
}

// SortedKeys is used by tests to prove the DTO and parser field sets agree.
func SortedKeys(shape reflect.Type) []string {
	keys := make([]string, 0, shape.NumField())
	for index := range shape.NumField() {
		if name, _ := jsonName(shape.Field(index)); name != "" {
			keys = append(keys, name)
		}
	}
	sort.Strings(keys)
	return keys
}

const parserSource = `const CONFIG_SOURCES: readonly ConfigSource[] = [
  'process',
  'target',
  'repository_file',
  'repository_panel',
  'template',
  'repository_path',
];
const LAYER_STATES: readonly FormattingLayerState[] = [
  'baseline',
  'stored',
  'draft',
  'absent',
  'bypassed',
];

export function parseSyncFileRenderResponse(value: unknown): SyncFileRenderResponse {
  const record = exactRecord(value, [
    'valid',
    'final_content',
    'matches_formatting',
    'diagnostics',
    'formatting',
  ]);
  if (
    record === null ||
    typeof record.valid !== 'boolean' ||
    typeof record.final_content !== 'string' ||
    typeof record.matches_formatting !== 'boolean' ||
    !Array.isArray(record.diagnostics)
  )
    throw new TypeError('invalid sync file render response');
  const diagnostics = record.diagnostics.map(parseDiagnostic);
  const formatting =
    record.formatting === undefined ? undefined : parseFormattingResolution(record.formatting);
  return {
    valid: record.valid,
    final_content: record.final_content,
    matches_formatting: record.matches_formatting,
    diagnostics,
    ...(formatting === undefined ? {} : { formatting }),
  };
}

function parseDiagnostic(value: unknown): SyncFileRenderDiagnostic {
  const record = exactRecord(value, ['stage', 'code', 'message']);
  if (
    record === null ||
    typeof record.stage !== 'string' ||
    typeof record.code !== 'string' ||
    typeof record.message !== 'string'
  )
    throw new TypeError('invalid sync file render diagnostic');
  return { stage: record.stage, code: record.code, message: record.message };
}

function parseFormattingResolution(value: unknown): SyncFileFormattingResolution {
  const record = exactRecord(value, [
    'current_layer',
    'inherited_policy',
    'effective_policy',
    'provenance',
    'layers',
  ]);
  const inherited = parseFormattingPolicy(record?.inherited_policy);
  const effective = parseFormattingPolicy(record?.effective_policy);
  const provenance = parseFormattingProvenance(record?.provenance);
  if (
    record === null ||
    !isOneOf(record.current_layer, CONFIG_SOURCES) ||
    inherited === null ||
    effective === null ||
    provenance === null ||
    !Array.isArray(record.layers)
  )
    throw new TypeError('invalid sync file formatting resolution');
  return {
    current_layer: record.current_layer,
    inherited_policy: inherited,
    effective_policy: effective,
    provenance,
    layers: record.layers.map(parseFormattingLayer),
  };
}

function parseFormattingLayer(value: unknown): SyncFileFormattingLayer {
  const record = exactRecord(value, ['source', 'state', 'formatting', 'config_path']);
  if (
    record === null ||
    !isOneOf(record.source, CONFIG_SOURCES) ||
    !isOneOf(record.state, LAYER_STATES) ||
    (record.config_path !== undefined && typeof record.config_path !== 'string')
  )
    throw new TypeError('invalid sync file formatting layer');
  let formatting: FormattingPatch | undefined;
  if (record.formatting !== undefined) {
    const parsed = parseFormattingPatch(record.formatting);
    if (parsed === null) throw new TypeError('invalid sync file formatting layer patch');
    formatting = parsed;
  }
  return {
    source: record.source,
    state: record.state,
    ...(formatting === undefined ? {} : { formatting }),
    ...(record.config_path === undefined ? {} : { config_path: record.config_path }),
  };
}

function parseFormattingProvenance(value: unknown): FormattingSources<ConfigSource> | null {
  return parseFormattingSources(value, CONFIG_SOURCES);
}

function exactRecord(value: unknown, allowed: readonly string[]): Record<string, unknown> | null {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return null;
  const record = value as Record<string, unknown>;
  return Object.keys(record).every((key) => allowed.includes(key)) ? record : null;
}

function isOneOf<Value extends string>(value: unknown, choices: readonly Value[]): value is Value {
  return typeof value === 'string' && choices.some((choice) => choice === value);
}
`
