// Code generated by internal/configgen. DO NOT EDIT.

export type FormattingPolicy = {
  'preset': 'preserve' | 'conventional';
  'common': {
    'indent_style': 'preserve' | 'spaces' | 'tabs';
    'indent_width': number;
    'line_width': number;
    'line_ending': 'preserve' | 'lf' | 'crlf';
    'final_newline': 'preserve' | 'insert' | 'remove';
  };
  'json': {
    'arrays': 'preserve' | 'auto' | 'compact' | 'expanded';
    'objects': 'preserve' | 'auto' | 'compact' | 'expanded';
    'key_order': 'preserve' | 'sort';
  };
  'jsonc': {
    'trailing_commas': 'preserve' | 'insert' | 'remove';
  };
  'yaml': {
    'sequences': 'preserve' | 'auto' | 'flow' | 'block';
    'mappings': 'preserve' | 'auto' | 'flow' | 'block';
    'quote_style': 'preserve' | 'prefer_plain' | 'prefer_single' | 'prefer_double';
    'sequence_indent': 'preserve' | 'indented' | 'indentless';
    'document_start': 'preserve' | 'insert' | 'remove';
  };
  'toml': {
    'arrays': 'preserve' | 'auto' | 'compact' | 'expanded';
    'trailing_commas': 'preserve' | 'multiline' | 'remove';
    'quote_style': 'preserve' | 'prefer_basic' | 'prefer_literal';
    'align_entries': 'preserve' | 'align' | 'compact';
    'align_comments': 'preserve' | 'align' | 'compact';
    'key_order': 'preserve' | 'sort';
  };
  'markdown': {
    'prose_wrap': 'preserve' | 'always' | 'never';
    'list_spacing': 'preserve' | 'tight' | 'loose';
    'tables': 'preserve' | 'align' | 'compact';
  };
};

type SparseFormatting<Value> = {
  [Key in keyof Value]?: Value[Key] extends object
    ? SparseFormatting<Value[Key]>
    : Value[Key];
};

export type FormattingPatch = SparseFormatting<FormattingPolicy>;

type FormattingSourceTree<Value, Source extends string> = {
  [Key in keyof Value]: Value[Key] extends object
    ? FormattingSourceTree<Value[Key], Source>
    : Source;
};

export type FormattingSources<Source extends string> = FormattingSourceTree<
  FormattingPolicy,
  Source
>;

export type FormattingPreset = FormattingPolicy['preset'];

export const FORMATTING_PRESETS = {
  'preserve': {
    'preset': 'preserve',
    'common': {
      'indent_style': 'preserve',
      'indent_width': 2,
      'line_width': 100,
      'line_ending': 'preserve',
      'final_newline': 'preserve',
    },
    'json': {
      'arrays': 'preserve',
      'objects': 'preserve',
      'key_order': 'preserve',
    },
    'jsonc': {
      'trailing_commas': 'preserve',
    },
    'yaml': {
      'sequences': 'preserve',
      'mappings': 'preserve',
      'quote_style': 'preserve',
      'sequence_indent': 'preserve',
      'document_start': 'preserve',
    },
    'toml': {
      'arrays': 'preserve',
      'trailing_commas': 'preserve',
      'quote_style': 'preserve',
      'align_entries': 'preserve',
      'align_comments': 'preserve',
      'key_order': 'preserve',
    },
    'markdown': {
      'prose_wrap': 'preserve',
      'list_spacing': 'preserve',
      'tables': 'preserve',
    },
  },
  'conventional': {
    'preset': 'conventional',
    'common': {
      'indent_style': 'spaces',
      'indent_width': 2,
      'line_width': 100,
      'line_ending': 'lf',
      'final_newline': 'insert',
    },
    'json': {
      'arrays': 'auto',
      'objects': 'auto',
      'key_order': 'preserve',
    },
    'jsonc': {
      'trailing_commas': 'preserve',
    },
    'yaml': {
      'sequences': 'auto',
      'mappings': 'block',
      'quote_style': 'preserve',
      'sequence_indent': 'preserve',
      'document_start': 'preserve',
    },
    'toml': {
      'arrays': 'auto',
      'trailing_commas': 'preserve',
      'quote_style': 'preserve',
      'align_entries': 'preserve',
      'align_comments': 'preserve',
      'key_order': 'preserve',
    },
    'markdown': {
      'prose_wrap': 'preserve',
      'list_spacing': 'preserve',
      'tables': 'align',
    },
  },
} as const satisfies Record<FormattingPreset, FormattingPolicy>;

export const FORMATTING_GROUPS = [
  { key: 'common', label: 'Common', description: 'Carries presentation choices shared by every supported format.' },
  { key: 'json', label: 'JSON', description: 'Carries strict JSON presentation choices.' },
  { key: 'jsonc', label: 'JSONC', description: 'Carries comment-aware JSON presentation choices.' },
  { key: 'yaml', label: 'YAML', description: 'Carries YAML presentation choices.' },
  { key: 'toml', label: 'TOML', description: 'Carries TOML presentation choices.' },
  { key: 'markdown', label: 'Markdown', description: 'Carries Markdown presentation choices.' },
] as const;

export type FormattingGroup = (typeof FORMATTING_GROUPS)[number];

export const FORMATTING_FIELDS = [
  {
    key: 'formatting.preset',
    path: ['preset'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'conventional'],
    description: 'Resets every formatting leaf before sibling overrides are applied.',
  },
  {
    key: 'formatting.common.indent_style',
    path: ['common', 'indent_style'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'spaces', 'tabs'],
    description: 'Chooses spaces, tabs, or the document\'s existing indentation.',
  },
  {
    key: 'formatting.common.indent_width',
    path: ['common', 'indent_width'],
    kind: 'int',
    defaultValue: 2,
    minimum: 1,
    maximum: 16,
    description: 'Is the number of spaces represented by one indentation level.',
  },
  {
    key: 'formatting.common.line_width',
    path: ['common', 'line_width'],
    kind: 'int',
    defaultValue: 100,
    minimum: 40,
    maximum: 320,
    description: 'Is the target width used by automatic collection and prose layout.',
  },
  {
    key: 'formatting.common.line_ending',
    path: ['common', 'line_ending'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'lf', 'crlf'],
    description: 'Chooses LF, CRLF, or the document\'s existing endings.',
  },
  {
    key: 'formatting.common.final_newline',
    path: ['common', 'final_newline'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'insert', 'remove'],
    description: 'Inserts, removes, or preserves the last line ending.',
  },
  {
    key: 'formatting.json.arrays',
    path: ['json', 'arrays'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'auto', 'compact', 'expanded'],
    description: 'Controls JSON array layout.',
  },
  {
    key: 'formatting.json.objects',
    path: ['json', 'objects'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'auto', 'compact', 'expanded'],
    description: 'Controls JSON object layout.',
  },
  {
    key: 'formatting.json.key_order',
    path: ['json', 'key_order'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'sort'],
    description: 'Preserves insertion order or sorts object keys.',
  },
  {
    key: 'formatting.jsonc.trailing_commas',
    path: ['jsonc', 'trailing_commas'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'insert', 'remove'],
    description: 'Inserts, removes, or preserves JSONC trailing commas.',
  },
  {
    key: 'formatting.yaml.sequences',
    path: ['yaml', 'sequences'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'auto', 'flow', 'block'],
    description: 'Controls YAML sequence layout.',
  },
  {
    key: 'formatting.yaml.mappings',
    path: ['yaml', 'mappings'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'auto', 'flow', 'block'],
    description: 'Controls YAML mapping layout.',
  },
  {
    key: 'formatting.yaml.quote_style',
    path: ['yaml', 'quote_style'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'prefer_plain', 'prefer_single', 'prefer_double'],
    description: 'Controls safe scalar quote preference.',
  },
  {
    key: 'formatting.yaml.sequence_indent',
    path: ['yaml', 'sequence_indent'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'indented', 'indentless'],
    description: 'Controls indentation of block sequence markers.',
  },
  {
    key: 'formatting.yaml.document_start',
    path: ['yaml', 'document_start'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'insert', 'remove'],
    description: 'Inserts, removes, or preserves the YAML document marker.',
  },
  {
    key: 'formatting.toml.arrays',
    path: ['toml', 'arrays'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'auto', 'compact', 'expanded'],
    description: 'Controls TOML array layout.',
  },
  {
    key: 'formatting.toml.trailing_commas',
    path: ['toml', 'trailing_commas'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'multiline', 'remove'],
    description: 'Controls commas in multiline TOML arrays.',
  },
  {
    key: 'formatting.toml.quote_style',
    path: ['toml', 'quote_style'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'prefer_basic', 'prefer_literal'],
    description: 'Controls safe TOML string quote preference.',
  },
  {
    key: 'formatting.toml.align_entries',
    path: ['toml', 'align_entries'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'align', 'compact'],
    description: 'Aligns or compacts neighbouring TOML assignments.',
  },
  {
    key: 'formatting.toml.align_comments',
    path: ['toml', 'align_comments'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'align', 'compact'],
    description: 'Aligns or compacts neighbouring TOML comments.',
  },
  {
    key: 'formatting.toml.key_order',
    path: ['toml', 'key_order'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'sort'],
    description: 'Preserves insertion order or sorts TOML keys.',
  },
  {
    key: 'formatting.markdown.prose_wrap',
    path: ['markdown', 'prose_wrap'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'always', 'never'],
    description: 'Wraps safe prose, removes soft wraps, or preserves it.',
  },
  {
    key: 'formatting.markdown.list_spacing',
    path: ['markdown', 'list_spacing'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'tight', 'loose'],
    description: 'Makes safe lists tight or loose, or preserves their spacing.',
  },
  {
    key: 'formatting.markdown.tables',
    path: ['markdown', 'tables'],
    kind: 'enum',
    defaultValue: 'preserve',
    options: ['preserve', 'align', 'compact'],
    description: 'Aligns or compacts safe GFM tables, or preserves them.',
  },
] as const;

export type FormattingField = (typeof FORMATTING_FIELDS)[number];
export type FormattingFieldKey = FormattingField['key'];
