// Code generated by internal/panelcontract. DO NOT EDIT.

import {
  parseFormattingPatch,
  parseFormattingPolicy,
  parseFormattingSources,
  type FormattingPatch,
  type FormattingPolicy,
  type FormattingSources,
} from './formatting';
import type { SyncFileMerge } from './types';

export type ConfigSource =
  'process' | 'target' | 'repository_file' | 'repository_panel' | 'template' | 'repository_path';

export type FormattingLayerState = 'baseline' | 'stored' | 'draft' | 'absent' | 'bypassed';

export interface SyncFileRenderInput {
  path: string;
  draft_content: string;
  template_formatting: FormattingPatch;
  repository?: SyncFileRenderRepositoryInput;
}

export interface SyncFileRenderRepositoryInput {
  id: string;
  merge?: Omit<SyncFileMerge, 'path'>;
  path_formatting: FormattingPatch;
}

export interface SyncFileRenderDiagnostic {
  stage: string;
  code: string;
  message: string;
}

export interface SyncFileFormattingLayer {
  source: ConfigSource;
  state: FormattingLayerState;
  formatting?: FormattingPatch;
  config_path?: string;
}

export interface SyncFileFormattingResolution {
  current_layer: ConfigSource;
  inherited_policy: FormattingPolicy;
  effective_policy: FormattingPolicy;
  provenance: FormattingSources<ConfigSource>;
  layers: SyncFileFormattingLayer[];
}

export interface SyncFileRenderResponse {
  valid: boolean;
  final_content: string;
  matches_formatting: boolean;
  diagnostics: SyncFileRenderDiagnostic[];
  formatting?: SyncFileFormattingResolution;
}

const CONFIG_SOURCES: readonly ConfigSource[] = [
  'process',
  'target',
  'repository_file',
  'repository_panel',
  'template',
  'repository_path',
];
const LAYER_STATES: readonly FormattingLayerState[] = [
  'baseline',
  'stored',
  'draft',
  'absent',
  'bypassed',
];

export function parseSyncFileRenderResponse(value: unknown): SyncFileRenderResponse {
  const record = exactRecord(value, [
    'valid',
    'final_content',
    'matches_formatting',
    'diagnostics',
    'formatting',
  ]);
  if (
    record === null ||
    typeof record.valid !== 'boolean' ||
    typeof record.final_content !== 'string' ||
    typeof record.matches_formatting !== 'boolean' ||
    !Array.isArray(record.diagnostics)
  )
    throw new TypeError('invalid sync file render response');
  const diagnostics = record.diagnostics.map(parseDiagnostic);
  const formatting =
    record.formatting === undefined ? undefined : parseFormattingResolution(record.formatting);
  return {
    valid: record.valid,
    final_content: record.final_content,
    matches_formatting: record.matches_formatting,
    diagnostics,
    ...(formatting === undefined ? {} : { formatting }),
  };
}

function parseDiagnostic(value: unknown): SyncFileRenderDiagnostic {
  const record = exactRecord(value, ['stage', 'code', 'message']);
  if (
    record === null ||
    typeof record.stage !== 'string' ||
    typeof record.code !== 'string' ||
    typeof record.message !== 'string'
  )
    throw new TypeError('invalid sync file render diagnostic');
  return { stage: record.stage, code: record.code, message: record.message };
}

function parseFormattingResolution(value: unknown): SyncFileFormattingResolution {
  const record = exactRecord(value, [
    'current_layer',
    'inherited_policy',
    'effective_policy',
    'provenance',
    'layers',
  ]);
  const inherited = parseFormattingPolicy(record?.inherited_policy);
  const effective = parseFormattingPolicy(record?.effective_policy);
  const provenance = parseFormattingProvenance(record?.provenance);
  if (
    record === null ||
    !isOneOf(record.current_layer, CONFIG_SOURCES) ||
    inherited === null ||
    effective === null ||
    provenance === null ||
    !Array.isArray(record.layers)
  )
    throw new TypeError('invalid sync file formatting resolution');
  return {
    current_layer: record.current_layer,
    inherited_policy: inherited,
    effective_policy: effective,
    provenance,
    layers: record.layers.map(parseFormattingLayer),
  };
}

function parseFormattingLayer(value: unknown): SyncFileFormattingLayer {
  const record = exactRecord(value, ['source', 'state', 'formatting', 'config_path']);
  if (
    record === null ||
    !isOneOf(record.source, CONFIG_SOURCES) ||
    !isOneOf(record.state, LAYER_STATES) ||
    (record.config_path !== undefined && typeof record.config_path !== 'string')
  )
    throw new TypeError('invalid sync file formatting layer');
  let formatting: FormattingPatch | undefined;
  if (record.formatting !== undefined) {
    const parsed = parseFormattingPatch(record.formatting);
    if (parsed === null) throw new TypeError('invalid sync file formatting layer patch');
    formatting = parsed;
  }
  return {
    source: record.source,
    state: record.state,
    ...(formatting === undefined ? {} : { formatting }),
    ...(record.config_path === undefined ? {} : { config_path: record.config_path }),
  };
}

function parseFormattingProvenance(value: unknown): FormattingSources<ConfigSource> | null {
  return parseFormattingSources(value, CONFIG_SOURCES);
}

function exactRecord(value: unknown, allowed: readonly string[]): Record<string, unknown> | null {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return null;
  const record = value as Record<string, unknown>;
  return Object.keys(record).every((key) => allowed.includes(key)) ? record : null;
}

function isOneOf<Value extends string>(value: unknown, choices: readonly Value[]): value is Value {
  return typeof value === 'string' && choices.some((choice) => choice === value);
}
