// Code generated by internal/configgen. DO NOT EDIT.

package config

// formattingPresetPolicy returns the complete policy declared by preset tags.
func formattingPresetPolicy(preset string) FormattingPolicy {
	switch preset {
	case "conventional":
		return FormattingPolicy{
			Preset: "conventional",
			Common: FormattingCommonPolicy{
				IndentStyle:  "spaces",
				IndentWidth:  2,
				LineWidth:    100,
				LineEnding:   "lf",
				FinalNewline: "insert",
			},
			JSON: FormattingJSONPolicy{
				Arrays:   "auto",
				Objects:  "auto",
				KeyOrder: "preserve",
			},
			JSONC: FormattingJSONCPolicy{
				TrailingCommas: "preserve",
			},
			YAML: FormattingYAMLPolicy{
				Sequences:      "auto",
				Mappings:       "block",
				QuoteStyle:     "preserve",
				SequenceIndent: "preserve",
				DocumentStart:  "preserve",
			},
			TOML: FormattingTOMLPolicy{
				Arrays:         "auto",
				TrailingCommas: "preserve",
				QuoteStyle:     "preserve",
				AlignEntries:   "preserve",
				AlignComments:  "preserve",
				KeyOrder:       "preserve",
			},
			Markdown: FormattingMarkdownPolicy{
				ProseWrap:   "preserve",
				ListSpacing: "preserve",
				Tables:      "align",
			},
		}
	default:
		return FormattingPolicy{
			Preset: "preserve",
			Common: FormattingCommonPolicy{
				IndentStyle:  "preserve",
				IndentWidth:  2,
				LineWidth:    100,
				LineEnding:   "preserve",
				FinalNewline: "preserve",
			},
			JSON: FormattingJSONPolicy{
				Arrays:   "preserve",
				Objects:  "preserve",
				KeyOrder: "preserve",
			},
			JSONC: FormattingJSONCPolicy{
				TrailingCommas: "preserve",
			},
			YAML: FormattingYAMLPolicy{
				Sequences:      "preserve",
				Mappings:       "preserve",
				QuoteStyle:     "preserve",
				SequenceIndent: "preserve",
				DocumentStart:  "preserve",
			},
			TOML: FormattingTOMLPolicy{
				Arrays:         "preserve",
				TrailingCommas: "preserve",
				QuoteStyle:     "preserve",
				AlignEntries:   "preserve",
				AlignComments:  "preserve",
				KeyOrder:       "preserve",
			},
			Markdown: FormattingMarkdownPolicy{
				ProseWrap:   "preserve",
				ListSpacing: "preserve",
				Tables:      "preserve",
			},
		}
	}
}
