// Code generated by internal/configgen. DO NOT EDIT.

package config

import (
	"maps"

	"github.com/spf13/pflag"
)

// Config is the effective configuration: every setting resolved to one value.
//
// It is the shape the rest of Smyklot reads. Patch is the shape a layer is
// written in, and this is what a stack of layers collapses to.
type Config struct {
	// Formatting controls file presentation independently of semantic merge.
	// Every dimension defaults to preserve, so adding the feature does not
	// rewrite an existing template.
	Formatting FormattingPolicy `json:"formatting"`

	// QuietSuccess drops the comment a successful command would post, leaving
	// only its reaction. Errors and warnings still comment.
	QuietSuccess bool `json:"quiet_success"`

	// QuietReactions drops the comment an approval or merge driven by a
	// reaction would post.
	QuietReactions bool `json:"quiet_reactions"`

	// QuietPending drops the comment announcing that a merge is waiting on CI,
	// leaving only its reaction.
	QuietPending bool `json:"quiet_pending"`

	// AllowedCommands narrows what may be run. An empty list allows every
	// command; naming any command forbids the rest.
	AllowedCommands []string `json:"allowed_commands"`

	// CommandAliases maps a spelling somebody uses onto the command it means,
	// such as "app" onto "approve".
	CommandAliases map[string]string `json:"command_aliases"`

	// CommandPrefix opens a slash-style command, as "/" does in "/approve".
	CommandPrefix string `json:"command_prefix"`

	// DisableMentions stops Smyklot answering a mention, such as "@smyklot
	// approve".
	DisableMentions bool `json:"disable_mentions"`

	// DisableBareCommands stops Smyklot answering an unprefixed word such as
	// "approve" or "lgtm" on a line of its own.
	DisableBareCommands bool `json:"disable_bare_commands"`

	// DisableUnapprove withdraws the unapprove and disapprove commands.
	DisableUnapprove bool `json:"disable_unapprove"`

	// DisableReactions stops a reaction on the pull request body counting as a
	// command at all.
	DisableReactions bool `json:"disable_reactions"`

	// DisableDeletedComments stops Smyklot reporting that a comment carrying a
	// command was deleted.
	DisableDeletedComments bool `json:"disable_deleted_comments"`

	// AllowSelfApproval lets the author of a pull request approve it. Off by
	// default: an approval is meant to be a second pair of eyes.
	AllowSelfApproval bool `json:"allow_self_approval"`

	// AllowDraftMerges lets a merge command mark a draft pull request ready
	// for review before continuing. Off by default: drafts stay protected
	// until a person explicitly publishes them.
	AllowDraftMerges bool `json:"allow_draft_merges"`

	// Runner names the entry point that acts on this repository, so the other
	// one stands down. It is settable only in the repository's own file: the
	// panel cannot write it, because a repository that has moved back to the
	// Action must be able to say so itself.
	Runner Runner `json:"runner"`
}

// Where the schema for this configuration is, spelled by the generator that
// wrote both it and this file.
//
// Generated rather than written twice, because three things have to agree: the
// document's own $id, the path the service answers at, and the directive the
// migration writes into a repository. A schema advertising an address nothing
// serves is the rot this generator exists to prevent.
const (
	// SchemaName is the schema document's file name.
	SchemaName = "repository-v1.json"

	// SchemaPath is where the service serves it, at the root of its origin
	// rather than under the panel: a schema is published documentation, and it
	// is served whether or not a deployment runs a panel at all.
	SchemaPath = "/schema/repository-v1.json"

	// SchemaURL is the published address, and what an editor is pointed at.
	SchemaURL = "https://smyklot.com/schema/repository-v1.json"
)

// The key every setting is addressed by, in a file, an environment variable,
// a command-line flag and the schema alike.
const (
	// KeyFormattingPreset addresses formatting.preset.
	KeyFormattingPreset = "formatting.preset"

	// KeyFormattingCommonIndentStyle addresses formatting.common.indent_style.
	KeyFormattingCommonIndentStyle = "formatting.common.indent_style"

	// KeyFormattingCommonIndentWidth addresses formatting.common.indent_width.
	KeyFormattingCommonIndentWidth = "formatting.common.indent_width"

	// KeyFormattingCommonLineWidth addresses formatting.common.line_width.
	KeyFormattingCommonLineWidth = "formatting.common.line_width"

	// KeyFormattingCommonLineEnding addresses formatting.common.line_ending.
	KeyFormattingCommonLineEnding = "formatting.common.line_ending"

	// KeyFormattingCommonFinalNewline addresses formatting.common.final_newline.
	KeyFormattingCommonFinalNewline = "formatting.common.final_newline"

	// KeyFormattingJSONArrays addresses formatting.json.arrays.
	KeyFormattingJSONArrays = "formatting.json.arrays"

	// KeyFormattingJSONObjects addresses formatting.json.objects.
	KeyFormattingJSONObjects = "formatting.json.objects"

	// KeyFormattingJSONKeyOrder addresses formatting.json.key_order.
	KeyFormattingJSONKeyOrder = "formatting.json.key_order"

	// KeyFormattingJSONCTrailingCommas addresses formatting.jsonc.trailing_commas.
	KeyFormattingJSONCTrailingCommas = "formatting.jsonc.trailing_commas"

	// KeyFormattingYAMLSequences addresses formatting.yaml.sequences.
	KeyFormattingYAMLSequences = "formatting.yaml.sequences"

	// KeyFormattingYAMLMappings addresses formatting.yaml.mappings.
	KeyFormattingYAMLMappings = "formatting.yaml.mappings"

	// KeyFormattingYAMLQuoteStyle addresses formatting.yaml.quote_style.
	KeyFormattingYAMLQuoteStyle = "formatting.yaml.quote_style"

	// KeyFormattingYAMLSequenceIndent addresses formatting.yaml.sequence_indent.
	KeyFormattingYAMLSequenceIndent = "formatting.yaml.sequence_indent"

	// KeyFormattingYAMLDocumentStart addresses formatting.yaml.document_start.
	KeyFormattingYAMLDocumentStart = "formatting.yaml.document_start"

	// KeyFormattingTOMLArrays addresses formatting.toml.arrays.
	KeyFormattingTOMLArrays = "formatting.toml.arrays"

	// KeyFormattingTOMLTrailingCommas addresses formatting.toml.trailing_commas.
	KeyFormattingTOMLTrailingCommas = "formatting.toml.trailing_commas"

	// KeyFormattingTOMLQuoteStyle addresses formatting.toml.quote_style.
	KeyFormattingTOMLQuoteStyle = "formatting.toml.quote_style"

	// KeyFormattingTOMLAlignEntries addresses formatting.toml.align_entries.
	KeyFormattingTOMLAlignEntries = "formatting.toml.align_entries"

	// KeyFormattingTOMLAlignComments addresses formatting.toml.align_comments.
	KeyFormattingTOMLAlignComments = "formatting.toml.align_comments"

	// KeyFormattingTOMLKeyOrder addresses formatting.toml.key_order.
	KeyFormattingTOMLKeyOrder = "formatting.toml.key_order"

	// KeyFormattingMarkdownProseWrap addresses formatting.markdown.prose_wrap.
	KeyFormattingMarkdownProseWrap = "formatting.markdown.prose_wrap"

	// KeyFormattingMarkdownListSpacing addresses formatting.markdown.list_spacing.
	KeyFormattingMarkdownListSpacing = "formatting.markdown.list_spacing"

	// KeyFormattingMarkdownTables addresses formatting.markdown.tables.
	KeyFormattingMarkdownTables = "formatting.markdown.tables"

	// KeyQuietSuccess addresses quiet_success.
	KeyQuietSuccess = "quiet_success"

	// KeyQuietReactions addresses quiet_reactions.
	KeyQuietReactions = "quiet_reactions"

	// KeyQuietPending addresses quiet_pending.
	KeyQuietPending = "quiet_pending"

	// KeyAllowedCommands addresses allowed_commands.
	KeyAllowedCommands = "allowed_commands"

	// KeyCommandAliases addresses command_aliases.
	KeyCommandAliases = "command_aliases"

	// KeyCommandPrefix addresses command_prefix.
	KeyCommandPrefix = "command_prefix"

	// KeyDisableMentions addresses disable_mentions.
	KeyDisableMentions = "disable_mentions"

	// KeyDisableBareCommands addresses disable_bare_commands.
	KeyDisableBareCommands = "disable_bare_commands"

	// KeyDisableUnapprove addresses disable_unapprove.
	KeyDisableUnapprove = "disable_unapprove"

	// KeyDisableReactions addresses disable_reactions.
	KeyDisableReactions = "disable_reactions"

	// KeyDisableDeletedComments addresses disable_deleted_comments.
	KeyDisableDeletedComments = "disable_deleted_comments"

	// KeyAllowSelfApproval addresses allow_self_approval.
	KeyAllowSelfApproval = "allow_self_approval"

	// KeyAllowDraftMerges addresses allow_draft_merges.
	KeyAllowDraftMerges = "allow_draft_merges"

	// KeyRunner addresses runner.
	KeyRunner = "runner"
)

// Default returns the configuration Smyklot runs with when nothing says
// otherwise. It is a fresh value every call: the slice and map fields are
// mutable, and a shared default would let one repository's resolution edit
// another's.
func Default() *Config {
	return &Config{
		Formatting:             DefaultFormattingPolicy(),
		QuietSuccess:           false,
		QuietReactions:         false,
		QuietPending:           false,
		AllowedCommands:        []string{},
		CommandAliases:         make(map[string]string),
		CommandPrefix:          "/",
		DisableMentions:        false,
		DisableBareCommands:    false,
		DisableUnapprove:       false,
		DisableReactions:       false,
		DisableDeletedComments: false,
		AllowSelfApproval:      false,
		AllowDraftMerges:       false,
		Runner:                 "service",
	}
}

// Keys returns every configuration key, in declaration order.
func Keys() []string {
	return []string{
		KeyFormattingPreset,
		KeyFormattingCommonIndentStyle,
		KeyFormattingCommonIndentWidth,
		KeyFormattingCommonLineWidth,
		KeyFormattingCommonLineEnding,
		KeyFormattingCommonFinalNewline,
		KeyFormattingJSONArrays,
		KeyFormattingJSONObjects,
		KeyFormattingJSONKeyOrder,
		KeyFormattingJSONCTrailingCommas,
		KeyFormattingYAMLSequences,
		KeyFormattingYAMLMappings,
		KeyFormattingYAMLQuoteStyle,
		KeyFormattingYAMLSequenceIndent,
		KeyFormattingYAMLDocumentStart,
		KeyFormattingTOMLArrays,
		KeyFormattingTOMLTrailingCommas,
		KeyFormattingTOMLQuoteStyle,
		KeyFormattingTOMLAlignEntries,
		KeyFormattingTOMLAlignComments,
		KeyFormattingTOMLKeyOrder,
		KeyFormattingMarkdownProseWrap,
		KeyFormattingMarkdownListSpacing,
		KeyFormattingMarkdownTables,
		KeyQuietSuccess,
		KeyQuietReactions,
		KeyQuietPending,
		KeyAllowedCommands,
		KeyCommandAliases,
		KeyCommandPrefix,
		KeyDisableMentions,
		KeyDisableBareCommands,
		KeyDisableUnapprove,
		KeyDisableReactions,
		KeyDisableDeletedComments,
		KeyAllowSelfApproval,
		KeyAllowDraftMerges,
		KeyRunner,
	}
}

// PanelDeniedKeys returns the settings the panel must refuse to write.
//
// A setting lands here by carrying `panel:"deny"` on Patch, so the rule
// lives beside the field it governs rather than in a second package that has to
// remember to keep up.
func PanelDeniedKeys() []string {
	return []string{
		KeyRunner,
	}
}

// AsPatch returns this configuration as a layer that sets every setting.
//
// The list and the mapping are copied rather than pointed at, so the patch does
// not alias the configuration it came from. A caller holding both would
// otherwise find that editing one edited the other.
func (c Config) AsPatch() Patch {
	formatting := c.Formatting.AsPatch()
	allowedCommands := append([]string{}, c.AllowedCommands...)
	commandAliases := maps.Clone(c.CommandAliases)

	return Patch{
		Formatting:             &formatting,
		QuietSuccess:           &c.QuietSuccess,
		QuietReactions:         &c.QuietReactions,
		QuietPending:           &c.QuietPending,
		AllowedCommands:        &allowedCommands,
		CommandAliases:         &commandAliases,
		CommandPrefix:          &c.CommandPrefix,
		DisableMentions:        &c.DisableMentions,
		DisableBareCommands:    &c.DisableBareCommands,
		DisableUnapprove:       &c.DisableUnapprove,
		DisableReactions:       &c.DisableReactions,
		DisableDeletedComments: &c.DisableDeletedComments,
		AllowSelfApproval:      &c.AllowSelfApproval,
		AllowDraftMerges:       &c.AllowDraftMerges,
		Runner:                 &c.Runner,
	}
}

// SetKeys returns the keys this patch sets, in declaration order.
//
// A patch is sparse, so "which settings does this layer speak to" is a question
// only the pointers can answer. Counting or enumerating them by hand is how a
// key comes to be left out of one caller and not another.
func (p Patch) SetKeys() []string {
	keys := make([]string, 0, 38)

	if p.Formatting != nil {
		keys = append(keys, p.Formatting.SetKeys()...)
	}

	if p.QuietSuccess != nil {
		keys = append(keys, KeyQuietSuccess)
	}

	if p.QuietReactions != nil {
		keys = append(keys, KeyQuietReactions)
	}

	if p.QuietPending != nil {
		keys = append(keys, KeyQuietPending)
	}

	if p.AllowedCommands != nil {
		keys = append(keys, KeyAllowedCommands)
	}

	if p.CommandAliases != nil {
		keys = append(keys, KeyCommandAliases)
	}

	if p.CommandPrefix != nil {
		keys = append(keys, KeyCommandPrefix)
	}

	if p.DisableMentions != nil {
		keys = append(keys, KeyDisableMentions)
	}

	if p.DisableBareCommands != nil {
		keys = append(keys, KeyDisableBareCommands)
	}

	if p.DisableUnapprove != nil {
		keys = append(keys, KeyDisableUnapprove)
	}

	if p.DisableReactions != nil {
		keys = append(keys, KeyDisableReactions)
	}

	if p.DisableDeletedComments != nil {
		keys = append(keys, KeyDisableDeletedComments)
	}

	if p.AllowSelfApproval != nil {
		keys = append(keys, KeyAllowSelfApproval)
	}

	if p.AllowDraftMerges != nil {
		keys = append(keys, KeyAllowDraftMerges)
	}

	if p.Runner != nil {
		keys = append(keys, KeyRunner)
	}

	return keys
}

// RegisterFlags defines a command-line flag for every setting that takes one,
// and --config-file, which names a document of them.
//
// A setting opts out with `flag:"-"` on Patch. The runner does, because it
// says which entry point acts on a repository and only the repository may
// answer that - a flag on the process would let one installation's deployment
// decide it for every repository it serves.
//
// This was written by hand and had fallen behind: quiet_pending had no flag at
// all, and nothing said so.
func RegisterFlags(flags *pflag.FlagSet) {
	defaults := Default()
	flags.String(FlagName(KeyFormattingPreset), defaults.Formatting.Preset, "Resets every formatting leaf before sibling overrides are applied")
	flags.String(FlagName(KeyFormattingCommonIndentStyle), defaults.Formatting.Common.IndentStyle, "Chooses spaces, tabs, or the document's existing indentation")
	flags.Int(FlagName(KeyFormattingCommonIndentWidth), defaults.Formatting.Common.IndentWidth, "Is the number of spaces represented by one indentation level")
	flags.Int(FlagName(KeyFormattingCommonLineWidth), defaults.Formatting.Common.LineWidth, "Is the target width used by automatic collection and prose layout")
	flags.String(FlagName(KeyFormattingCommonLineEnding), defaults.Formatting.Common.LineEnding, "Chooses LF, CRLF, or the document's existing endings")
	flags.String(FlagName(KeyFormattingCommonFinalNewline), defaults.Formatting.Common.FinalNewline, "Inserts, removes, or preserves the last line ending")
	flags.String(FlagName(KeyFormattingJSONArrays), defaults.Formatting.JSON.Arrays, "Controls JSON array layout")
	flags.String(FlagName(KeyFormattingJSONObjects), defaults.Formatting.JSON.Objects, "Controls JSON object layout")
	flags.String(FlagName(KeyFormattingJSONKeyOrder), defaults.Formatting.JSON.KeyOrder, "Preserves insertion order or sorts object keys")
	flags.String(FlagName(KeyFormattingJSONCTrailingCommas), defaults.Formatting.JSONC.TrailingCommas, "Inserts, removes, or preserves JSONC trailing commas")
	flags.String(FlagName(KeyFormattingYAMLSequences), defaults.Formatting.YAML.Sequences, "Controls YAML sequence layout")
	flags.String(FlagName(KeyFormattingYAMLMappings), defaults.Formatting.YAML.Mappings, "Controls YAML mapping layout")
	flags.String(FlagName(KeyFormattingYAMLQuoteStyle), defaults.Formatting.YAML.QuoteStyle, "Controls safe scalar quote preference")
	flags.String(FlagName(KeyFormattingYAMLSequenceIndent), defaults.Formatting.YAML.SequenceIndent, "Controls indentation of block sequence markers")
	flags.String(FlagName(KeyFormattingYAMLDocumentStart), defaults.Formatting.YAML.DocumentStart, "Inserts, removes, or preserves the YAML document marker")
	flags.String(FlagName(KeyFormattingTOMLArrays), defaults.Formatting.TOML.Arrays, "Controls TOML array layout")
	flags.String(FlagName(KeyFormattingTOMLTrailingCommas), defaults.Formatting.TOML.TrailingCommas, "Controls commas in multiline TOML arrays")
	flags.String(FlagName(KeyFormattingTOMLQuoteStyle), defaults.Formatting.TOML.QuoteStyle, "Controls safe TOML string quote preference")
	flags.String(FlagName(KeyFormattingTOMLAlignEntries), defaults.Formatting.TOML.AlignEntries, "Aligns or compacts neighbouring TOML assignments")
	flags.String(FlagName(KeyFormattingTOMLAlignComments), defaults.Formatting.TOML.AlignComments, "Aligns or compacts neighbouring TOML comments")
	flags.String(FlagName(KeyFormattingTOMLKeyOrder), defaults.Formatting.TOML.KeyOrder, "Preserves insertion order or sorts TOML keys")
	flags.String(FlagName(KeyFormattingMarkdownProseWrap), defaults.Formatting.Markdown.ProseWrap, "Wraps safe prose, removes soft wraps, or preserves it")
	flags.String(FlagName(KeyFormattingMarkdownListSpacing), defaults.Formatting.Markdown.ListSpacing, "Makes safe lists tight or loose, or preserves their spacing")
	flags.String(FlagName(KeyFormattingMarkdownTables), defaults.Formatting.Markdown.Tables, "Aligns or compacts safe GFM tables, or preserves them")
	flags.Bool(FlagName(KeyQuietSuccess), defaults.QuietSuccess, "Drops the comment a successful command would post, leaving only its reaction. Errors and warnings still comment")
	flags.Bool(FlagName(KeyQuietReactions), defaults.QuietReactions, "Drops the comment an approval or merge driven by a reaction would post")
	flags.Bool(FlagName(KeyQuietPending), defaults.QuietPending, "Drops the comment announcing that a merge is waiting on CI, leaving only its reaction")
	flags.StringSlice(FlagName(KeyAllowedCommands), defaults.AllowedCommands, "Narrows what may be run. An empty list allows every command; naming any command forbids the rest")
	flags.StringToString(FlagName(KeyCommandAliases), defaults.CommandAliases, "Maps a spelling somebody uses onto the command it means, such as \"app\" onto \"approve\"")
	flags.String(FlagName(KeyCommandPrefix), defaults.CommandPrefix, "Opens a slash-style command, as \"/\" does in \"/approve\"")
	flags.Bool(FlagName(KeyDisableMentions), defaults.DisableMentions, "Stops Smyklot answering a mention, such as \"@smyklot approve\"")
	flags.Bool(FlagName(KeyDisableBareCommands), defaults.DisableBareCommands, "Stops Smyklot answering an unprefixed word such as \"approve\" or \"lgtm\" on a line of its own")
	flags.Bool(FlagName(KeyDisableUnapprove), defaults.DisableUnapprove, "Withdraws the unapprove and disapprove commands")
	flags.Bool(FlagName(KeyDisableReactions), defaults.DisableReactions, "Stops a reaction on the pull request body counting as a command at all")
	flags.Bool(FlagName(KeyDisableDeletedComments), defaults.DisableDeletedComments, "Stops Smyklot reporting that a comment carrying a command was deleted")
	flags.Bool(FlagName(KeyAllowSelfApproval), defaults.AllowSelfApproval, "Lets the author of a pull request approve it. Off by default: an approval is meant to be a second pair of eyes")
	flags.Bool(FlagName(KeyAllowDraftMerges), defaults.AllowDraftMerges, "Lets a merge command mark a draft pull request ready for review before continuing. Off by default: drafts stay protected until a person explicitly publishes them")

	registerConfigFileFlag(flags)
}

// normalize turns whatever a decoder or a variable produced into a value this
// package vouches for.
//
// A setting whose Go type this package declares is only text until its own
// parser has seen it, and every layer reads text: a file, a document, a
// variable, a flag. Running this once in the resolver is what stops a typo
// being caught in a repository's file and waved through in an environment
// variable. The pointer is replaced rather than written through, since a patch
// may point into a Config that nothing asked to have edited.
func (p *Patch) normalize() error {
	if p.Formatting != nil {
		if err := p.Formatting.normalize(); err != nil {
			return err
		}
	}

	if p.Runner != nil {
		value, err := ParseRunner(string(*p.Runner))
		if err != nil {
			return err
		}
		p.Runner = &value
	}

	return nil
}

// envPatch reads the layer written one variable per setting.
//
// A variable set to nothing counts as unset. A workflow that forwards an input
// nobody filled in writes an empty string, and reading that as an instruction
// would let a missing input narrow allowed_commands to nothing - on the layer
// stack that is fail-closed, so every command would be refused. viper read it
// the same way, for the same reason.
func envPatch(lookup func(string) (string, bool)) (Patch, error) {
	var patch Patch

	if raw, ok := lookup(EnvVar(KeyFormattingPreset)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		patch.Formatting.Preset = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingCommonIndentStyle)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.Common == nil {
			patch.Formatting.Common = &FormattingCommonPatch{}
		}
		patch.Formatting.Common.IndentStyle = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingCommonIndentWidth)); ok && raw != "" {
		value, err := parseInt(KeyFormattingCommonIndentWidth, raw)
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.Common == nil {
			patch.Formatting.Common = &FormattingCommonPatch{}
		}
		patch.Formatting.Common.IndentWidth = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingCommonLineWidth)); ok && raw != "" {
		value, err := parseInt(KeyFormattingCommonLineWidth, raw)
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.Common == nil {
			patch.Formatting.Common = &FormattingCommonPatch{}
		}
		patch.Formatting.Common.LineWidth = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingCommonLineEnding)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.Common == nil {
			patch.Formatting.Common = &FormattingCommonPatch{}
		}
		patch.Formatting.Common.LineEnding = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingCommonFinalNewline)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.Common == nil {
			patch.Formatting.Common = &FormattingCommonPatch{}
		}
		patch.Formatting.Common.FinalNewline = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingJSONArrays)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.JSON == nil {
			patch.Formatting.JSON = &FormattingJSONPatch{}
		}
		patch.Formatting.JSON.Arrays = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingJSONObjects)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.JSON == nil {
			patch.Formatting.JSON = &FormattingJSONPatch{}
		}
		patch.Formatting.JSON.Objects = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingJSONKeyOrder)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.JSON == nil {
			patch.Formatting.JSON = &FormattingJSONPatch{}
		}
		patch.Formatting.JSON.KeyOrder = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingJSONCTrailingCommas)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.JSONC == nil {
			patch.Formatting.JSONC = &FormattingJSONCPatch{}
		}
		patch.Formatting.JSONC.TrailingCommas = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingYAMLSequences)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.YAML == nil {
			patch.Formatting.YAML = &FormattingYAMLPatch{}
		}
		patch.Formatting.YAML.Sequences = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingYAMLMappings)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.YAML == nil {
			patch.Formatting.YAML = &FormattingYAMLPatch{}
		}
		patch.Formatting.YAML.Mappings = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingYAMLQuoteStyle)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.YAML == nil {
			patch.Formatting.YAML = &FormattingYAMLPatch{}
		}
		patch.Formatting.YAML.QuoteStyle = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingYAMLSequenceIndent)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.YAML == nil {
			patch.Formatting.YAML = &FormattingYAMLPatch{}
		}
		patch.Formatting.YAML.SequenceIndent = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingYAMLDocumentStart)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.YAML == nil {
			patch.Formatting.YAML = &FormattingYAMLPatch{}
		}
		patch.Formatting.YAML.DocumentStart = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingTOMLArrays)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.TOML == nil {
			patch.Formatting.TOML = &FormattingTOMLPatch{}
		}
		patch.Formatting.TOML.Arrays = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingTOMLTrailingCommas)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.TOML == nil {
			patch.Formatting.TOML = &FormattingTOMLPatch{}
		}
		patch.Formatting.TOML.TrailingCommas = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingTOMLQuoteStyle)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.TOML == nil {
			patch.Formatting.TOML = &FormattingTOMLPatch{}
		}
		patch.Formatting.TOML.QuoteStyle = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingTOMLAlignEntries)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.TOML == nil {
			patch.Formatting.TOML = &FormattingTOMLPatch{}
		}
		patch.Formatting.TOML.AlignEntries = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingTOMLAlignComments)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.TOML == nil {
			patch.Formatting.TOML = &FormattingTOMLPatch{}
		}
		patch.Formatting.TOML.AlignComments = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingTOMLKeyOrder)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.TOML == nil {
			patch.Formatting.TOML = &FormattingTOMLPatch{}
		}
		patch.Formatting.TOML.KeyOrder = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingMarkdownProseWrap)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.Markdown == nil {
			patch.Formatting.Markdown = &FormattingMarkdownPatch{}
		}
		patch.Formatting.Markdown.ProseWrap = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingMarkdownListSpacing)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.Markdown == nil {
			patch.Formatting.Markdown = &FormattingMarkdownPatch{}
		}
		patch.Formatting.Markdown.ListSpacing = &value
	}

	if raw, ok := lookup(EnvVar(KeyFormattingMarkdownTables)); ok && raw != "" {
		value := raw
		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.Markdown == nil {
			patch.Formatting.Markdown = &FormattingMarkdownPatch{}
		}
		patch.Formatting.Markdown.Tables = &value
	}

	if raw, ok := lookup(EnvVar(KeyQuietSuccess)); ok && raw != "" {
		value, err := parseBool(KeyQuietSuccess, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.QuietSuccess = &value
	}

	if raw, ok := lookup(EnvVar(KeyQuietReactions)); ok && raw != "" {
		value, err := parseBool(KeyQuietReactions, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.QuietReactions = &value
	}

	if raw, ok := lookup(EnvVar(KeyQuietPending)); ok && raw != "" {
		value, err := parseBool(KeyQuietPending, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.QuietPending = &value
	}

	if raw, ok := lookup(EnvVar(KeyAllowedCommands)); ok && raw != "" {
		value := parseList(raw)
		patch.AllowedCommands = &value
	}

	if raw, ok := lookup(EnvVar(KeyCommandAliases)); ok && raw != "" {
		value, err := parseMapping(KeyCommandAliases, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.CommandAliases = &value
	}

	if raw, ok := lookup(EnvVar(KeyCommandPrefix)); ok && raw != "" {
		value := raw
		patch.CommandPrefix = &value
	}

	if raw, ok := lookup(EnvVar(KeyDisableMentions)); ok && raw != "" {
		value, err := parseBool(KeyDisableMentions, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.DisableMentions = &value
	}

	if raw, ok := lookup(EnvVar(KeyDisableBareCommands)); ok && raw != "" {
		value, err := parseBool(KeyDisableBareCommands, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.DisableBareCommands = &value
	}

	if raw, ok := lookup(EnvVar(KeyDisableUnapprove)); ok && raw != "" {
		value, err := parseBool(KeyDisableUnapprove, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.DisableUnapprove = &value
	}

	if raw, ok := lookup(EnvVar(KeyDisableReactions)); ok && raw != "" {
		value, err := parseBool(KeyDisableReactions, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.DisableReactions = &value
	}

	if raw, ok := lookup(EnvVar(KeyDisableDeletedComments)); ok && raw != "" {
		value, err := parseBool(KeyDisableDeletedComments, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.DisableDeletedComments = &value
	}

	if raw, ok := lookup(EnvVar(KeyAllowSelfApproval)); ok && raw != "" {
		value, err := parseBool(KeyAllowSelfApproval, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.AllowSelfApproval = &value
	}

	if raw, ok := lookup(EnvVar(KeyAllowDraftMerges)); ok && raw != "" {
		value, err := parseBool(KeyAllowDraftMerges, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.AllowDraftMerges = &value
	}

	if raw, ok := lookup(EnvVar(KeyRunner)); ok && raw != "" {
		value := Runner(raw)
		patch.Runner = &value
	}

	return patch, nil
}

// flagPatch reads the layer given on the command line.
//
// Changed is what makes this a patch rather than a whole configuration: a flag
// carries its default whether or not anyone passed it, and applying those
// defaults over the layers below would let the command line silently outrank a
// file it never mentioned. A flag no command registered reports false, so an
// entry point that takes fewer of them needs no special case.
func flagPatch(flags *pflag.FlagSet) (Patch, error) {
	var patch Patch

	if flags == nil {
		return patch, nil
	}

	if flags.Changed(FlagName(KeyFormattingPreset)) {
		value, err := flags.GetString(FlagName(KeyFormattingPreset))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		patch.Formatting.Preset = &value
	}

	if flags.Changed(FlagName(KeyFormattingCommonIndentStyle)) {
		value, err := flags.GetString(FlagName(KeyFormattingCommonIndentStyle))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.Common == nil {
			patch.Formatting.Common = &FormattingCommonPatch{}
		}
		patch.Formatting.Common.IndentStyle = &value
	}

	if flags.Changed(FlagName(KeyFormattingCommonIndentWidth)) {
		value, err := flags.GetInt(FlagName(KeyFormattingCommonIndentWidth))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.Common == nil {
			patch.Formatting.Common = &FormattingCommonPatch{}
		}
		patch.Formatting.Common.IndentWidth = &value
	}

	if flags.Changed(FlagName(KeyFormattingCommonLineWidth)) {
		value, err := flags.GetInt(FlagName(KeyFormattingCommonLineWidth))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.Common == nil {
			patch.Formatting.Common = &FormattingCommonPatch{}
		}
		patch.Formatting.Common.LineWidth = &value
	}

	if flags.Changed(FlagName(KeyFormattingCommonLineEnding)) {
		value, err := flags.GetString(FlagName(KeyFormattingCommonLineEnding))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.Common == nil {
			patch.Formatting.Common = &FormattingCommonPatch{}
		}
		patch.Formatting.Common.LineEnding = &value
	}

	if flags.Changed(FlagName(KeyFormattingCommonFinalNewline)) {
		value, err := flags.GetString(FlagName(KeyFormattingCommonFinalNewline))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.Common == nil {
			patch.Formatting.Common = &FormattingCommonPatch{}
		}
		patch.Formatting.Common.FinalNewline = &value
	}

	if flags.Changed(FlagName(KeyFormattingJSONArrays)) {
		value, err := flags.GetString(FlagName(KeyFormattingJSONArrays))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.JSON == nil {
			patch.Formatting.JSON = &FormattingJSONPatch{}
		}
		patch.Formatting.JSON.Arrays = &value
	}

	if flags.Changed(FlagName(KeyFormattingJSONObjects)) {
		value, err := flags.GetString(FlagName(KeyFormattingJSONObjects))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.JSON == nil {
			patch.Formatting.JSON = &FormattingJSONPatch{}
		}
		patch.Formatting.JSON.Objects = &value
	}

	if flags.Changed(FlagName(KeyFormattingJSONKeyOrder)) {
		value, err := flags.GetString(FlagName(KeyFormattingJSONKeyOrder))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.JSON == nil {
			patch.Formatting.JSON = &FormattingJSONPatch{}
		}
		patch.Formatting.JSON.KeyOrder = &value
	}

	if flags.Changed(FlagName(KeyFormattingJSONCTrailingCommas)) {
		value, err := flags.GetString(FlagName(KeyFormattingJSONCTrailingCommas))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.JSONC == nil {
			patch.Formatting.JSONC = &FormattingJSONCPatch{}
		}
		patch.Formatting.JSONC.TrailingCommas = &value
	}

	if flags.Changed(FlagName(KeyFormattingYAMLSequences)) {
		value, err := flags.GetString(FlagName(KeyFormattingYAMLSequences))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.YAML == nil {
			patch.Formatting.YAML = &FormattingYAMLPatch{}
		}
		patch.Formatting.YAML.Sequences = &value
	}

	if flags.Changed(FlagName(KeyFormattingYAMLMappings)) {
		value, err := flags.GetString(FlagName(KeyFormattingYAMLMappings))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.YAML == nil {
			patch.Formatting.YAML = &FormattingYAMLPatch{}
		}
		patch.Formatting.YAML.Mappings = &value
	}

	if flags.Changed(FlagName(KeyFormattingYAMLQuoteStyle)) {
		value, err := flags.GetString(FlagName(KeyFormattingYAMLQuoteStyle))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.YAML == nil {
			patch.Formatting.YAML = &FormattingYAMLPatch{}
		}
		patch.Formatting.YAML.QuoteStyle = &value
	}

	if flags.Changed(FlagName(KeyFormattingYAMLSequenceIndent)) {
		value, err := flags.GetString(FlagName(KeyFormattingYAMLSequenceIndent))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.YAML == nil {
			patch.Formatting.YAML = &FormattingYAMLPatch{}
		}
		patch.Formatting.YAML.SequenceIndent = &value
	}

	if flags.Changed(FlagName(KeyFormattingYAMLDocumentStart)) {
		value, err := flags.GetString(FlagName(KeyFormattingYAMLDocumentStart))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.YAML == nil {
			patch.Formatting.YAML = &FormattingYAMLPatch{}
		}
		patch.Formatting.YAML.DocumentStart = &value
	}

	if flags.Changed(FlagName(KeyFormattingTOMLArrays)) {
		value, err := flags.GetString(FlagName(KeyFormattingTOMLArrays))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.TOML == nil {
			patch.Formatting.TOML = &FormattingTOMLPatch{}
		}
		patch.Formatting.TOML.Arrays = &value
	}

	if flags.Changed(FlagName(KeyFormattingTOMLTrailingCommas)) {
		value, err := flags.GetString(FlagName(KeyFormattingTOMLTrailingCommas))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.TOML == nil {
			patch.Formatting.TOML = &FormattingTOMLPatch{}
		}
		patch.Formatting.TOML.TrailingCommas = &value
	}

	if flags.Changed(FlagName(KeyFormattingTOMLQuoteStyle)) {
		value, err := flags.GetString(FlagName(KeyFormattingTOMLQuoteStyle))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.TOML == nil {
			patch.Formatting.TOML = &FormattingTOMLPatch{}
		}
		patch.Formatting.TOML.QuoteStyle = &value
	}

	if flags.Changed(FlagName(KeyFormattingTOMLAlignEntries)) {
		value, err := flags.GetString(FlagName(KeyFormattingTOMLAlignEntries))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.TOML == nil {
			patch.Formatting.TOML = &FormattingTOMLPatch{}
		}
		patch.Formatting.TOML.AlignEntries = &value
	}

	if flags.Changed(FlagName(KeyFormattingTOMLAlignComments)) {
		value, err := flags.GetString(FlagName(KeyFormattingTOMLAlignComments))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.TOML == nil {
			patch.Formatting.TOML = &FormattingTOMLPatch{}
		}
		patch.Formatting.TOML.AlignComments = &value
	}

	if flags.Changed(FlagName(KeyFormattingTOMLKeyOrder)) {
		value, err := flags.GetString(FlagName(KeyFormattingTOMLKeyOrder))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.TOML == nil {
			patch.Formatting.TOML = &FormattingTOMLPatch{}
		}
		patch.Formatting.TOML.KeyOrder = &value
	}

	if flags.Changed(FlagName(KeyFormattingMarkdownProseWrap)) {
		value, err := flags.GetString(FlagName(KeyFormattingMarkdownProseWrap))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.Markdown == nil {
			patch.Formatting.Markdown = &FormattingMarkdownPatch{}
		}
		patch.Formatting.Markdown.ProseWrap = &value
	}

	if flags.Changed(FlagName(KeyFormattingMarkdownListSpacing)) {
		value, err := flags.GetString(FlagName(KeyFormattingMarkdownListSpacing))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.Markdown == nil {
			patch.Formatting.Markdown = &FormattingMarkdownPatch{}
		}
		patch.Formatting.Markdown.ListSpacing = &value
	}

	if flags.Changed(FlagName(KeyFormattingMarkdownTables)) {
		value, err := flags.GetString(FlagName(KeyFormattingMarkdownTables))
		if err != nil {
			return Patch{}, err
		}

		if patch.Formatting == nil {
			patch.Formatting = &FormattingPatch{}
		}
		if patch.Formatting.Markdown == nil {
			patch.Formatting.Markdown = &FormattingMarkdownPatch{}
		}
		patch.Formatting.Markdown.Tables = &value
	}

	if flags.Changed(FlagName(KeyQuietSuccess)) {
		value, err := flags.GetBool(FlagName(KeyQuietSuccess))
		if err != nil {
			return Patch{}, err
		}

		patch.QuietSuccess = &value
	}

	if flags.Changed(FlagName(KeyQuietReactions)) {
		value, err := flags.GetBool(FlagName(KeyQuietReactions))
		if err != nil {
			return Patch{}, err
		}

		patch.QuietReactions = &value
	}

	if flags.Changed(FlagName(KeyQuietPending)) {
		value, err := flags.GetBool(FlagName(KeyQuietPending))
		if err != nil {
			return Patch{}, err
		}

		patch.QuietPending = &value
	}

	if flags.Changed(FlagName(KeyAllowedCommands)) {
		value, err := flags.GetStringSlice(FlagName(KeyAllowedCommands))
		if err != nil {
			return Patch{}, err
		}

		patch.AllowedCommands = &value
	}

	if flags.Changed(FlagName(KeyCommandAliases)) {
		value, err := flags.GetStringToString(FlagName(KeyCommandAliases))
		if err != nil {
			return Patch{}, err
		}

		patch.CommandAliases = &value
	}

	if flags.Changed(FlagName(KeyCommandPrefix)) {
		value, err := flags.GetString(FlagName(KeyCommandPrefix))
		if err != nil {
			return Patch{}, err
		}

		patch.CommandPrefix = &value
	}

	if flags.Changed(FlagName(KeyDisableMentions)) {
		value, err := flags.GetBool(FlagName(KeyDisableMentions))
		if err != nil {
			return Patch{}, err
		}

		patch.DisableMentions = &value
	}

	if flags.Changed(FlagName(KeyDisableBareCommands)) {
		value, err := flags.GetBool(FlagName(KeyDisableBareCommands))
		if err != nil {
			return Patch{}, err
		}

		patch.DisableBareCommands = &value
	}

	if flags.Changed(FlagName(KeyDisableUnapprove)) {
		value, err := flags.GetBool(FlagName(KeyDisableUnapprove))
		if err != nil {
			return Patch{}, err
		}

		patch.DisableUnapprove = &value
	}

	if flags.Changed(FlagName(KeyDisableReactions)) {
		value, err := flags.GetBool(FlagName(KeyDisableReactions))
		if err != nil {
			return Patch{}, err
		}

		patch.DisableReactions = &value
	}

	if flags.Changed(FlagName(KeyDisableDeletedComments)) {
		value, err := flags.GetBool(FlagName(KeyDisableDeletedComments))
		if err != nil {
			return Patch{}, err
		}

		patch.DisableDeletedComments = &value
	}

	if flags.Changed(FlagName(KeyAllowSelfApproval)) {
		value, err := flags.GetBool(FlagName(KeyAllowSelfApproval))
		if err != nil {
			return Patch{}, err
		}

		patch.AllowSelfApproval = &value
	}

	if flags.Changed(FlagName(KeyAllowDraftMerges)) {
		value, err := flags.GetBool(FlagName(KeyAllowDraftMerges))
		if err != nil {
			return Patch{}, err
		}

		patch.AllowDraftMerges = &value
	}

	return patch, nil
}

func applyPatch(values *Config, patch Patch, sources map[string]Source, source Source) {
	if patch.Formatting != nil {
		applyFormattingPatch(&values.Formatting, *patch.Formatting, sources, source)
	}
	set(&values.QuietSuccess, patch.QuietSuccess, sources, KeyQuietSuccess, source)
	set(&values.QuietReactions, patch.QuietReactions, sources, KeyQuietReactions, source)
	set(&values.QuietPending, patch.QuietPending, sources, KeyQuietPending, source)
	setSlice(&values.AllowedCommands, patch.AllowedCommands, sources, KeyAllowedCommands, source)
	setMap(&values.CommandAliases, patch.CommandAliases, sources, KeyCommandAliases, source)
	set(&values.CommandPrefix, patch.CommandPrefix, sources, KeyCommandPrefix, source)
	set(&values.DisableMentions, patch.DisableMentions, sources, KeyDisableMentions, source)
	set(&values.DisableBareCommands, patch.DisableBareCommands, sources, KeyDisableBareCommands, source)
	set(&values.DisableUnapprove, patch.DisableUnapprove, sources, KeyDisableUnapprove, source)
	set(&values.DisableReactions, patch.DisableReactions, sources, KeyDisableReactions, source)
	set(&values.DisableDeletedComments, patch.DisableDeletedComments, sources, KeyDisableDeletedComments, source)
	set(&values.AllowSelfApproval, patch.AllowSelfApproval, sources, KeyAllowSelfApproval, source)
	set(&values.AllowDraftMerges, patch.AllowDraftMerges, sources, KeyAllowDraftMerges, source)
	set(&values.Runner, patch.Runner, sources, KeyRunner, source)
}

func processSources() map[string]Source {
	return map[string]Source{
		KeyFormattingPreset:              SourceProcess,
		KeyFormattingCommonIndentStyle:   SourceProcess,
		KeyFormattingCommonIndentWidth:   SourceProcess,
		KeyFormattingCommonLineWidth:     SourceProcess,
		KeyFormattingCommonLineEnding:    SourceProcess,
		KeyFormattingCommonFinalNewline:  SourceProcess,
		KeyFormattingJSONArrays:          SourceProcess,
		KeyFormattingJSONObjects:         SourceProcess,
		KeyFormattingJSONKeyOrder:        SourceProcess,
		KeyFormattingJSONCTrailingCommas: SourceProcess,
		KeyFormattingYAMLSequences:       SourceProcess,
		KeyFormattingYAMLMappings:        SourceProcess,
		KeyFormattingYAMLQuoteStyle:      SourceProcess,
		KeyFormattingYAMLSequenceIndent:  SourceProcess,
		KeyFormattingYAMLDocumentStart:   SourceProcess,
		KeyFormattingTOMLArrays:          SourceProcess,
		KeyFormattingTOMLTrailingCommas:  SourceProcess,
		KeyFormattingTOMLQuoteStyle:      SourceProcess,
		KeyFormattingTOMLAlignEntries:    SourceProcess,
		KeyFormattingTOMLAlignComments:   SourceProcess,
		KeyFormattingTOMLKeyOrder:        SourceProcess,
		KeyFormattingMarkdownProseWrap:   SourceProcess,
		KeyFormattingMarkdownListSpacing: SourceProcess,
		KeyFormattingMarkdownTables:      SourceProcess,
		KeyQuietSuccess:                  SourceProcess,
		KeyQuietReactions:                SourceProcess,
		KeyQuietPending:                  SourceProcess,
		KeyAllowedCommands:               SourceProcess,
		KeyCommandAliases:                SourceProcess,
		KeyCommandPrefix:                 SourceProcess,
		KeyDisableMentions:               SourceProcess,
		KeyDisableBareCommands:           SourceProcess,
		KeyDisableUnapprove:              SourceProcess,
		KeyDisableReactions:              SourceProcess,
		KeyDisableDeletedComments:        SourceProcess,
		KeyAllowSelfApproval:             SourceProcess,
		KeyAllowDraftMerges:              SourceProcess,
		KeyRunner:                        SourceProcess,
	}
}
