// Code generated by internal/configgen. DO NOT EDIT.

package config

import (
	"maps"

	"github.com/spf13/pflag"
)

// Config is the effective configuration: every setting resolved to one value.
//
// It is the shape the rest of Smyklot reads. Patch is the shape a layer is
// written in, and this is what a stack of layers collapses to.
type Config struct {
	// QuietSuccess drops the comment a successful command would post, leaving
	// only its reaction. Errors and warnings still comment.
	QuietSuccess bool `json:"quiet_success"`

	// QuietReactions drops the comment an approval or merge driven by a
	// reaction would post.
	QuietReactions bool `json:"quiet_reactions"`

	// QuietPending drops the comment announcing that a merge is waiting on CI,
	// leaving only its reaction.
	QuietPending bool `json:"quiet_pending"`

	// AllowedCommands narrows what may be run. An empty list allows every
	// command; naming any command forbids the rest.
	AllowedCommands []string `json:"allowed_commands"`

	// CommandAliases maps a spelling somebody uses onto the command it means,
	// such as "app" onto "approve".
	CommandAliases map[string]string `json:"command_aliases"`

	// CommandPrefix opens a slash-style command, as "/" does in "/approve".
	CommandPrefix string `json:"command_prefix"`

	// DisableMentions stops Smyklot answering a mention, such as "@smyklot
	// approve".
	DisableMentions bool `json:"disable_mentions"`

	// DisableBareCommands stops Smyklot answering an unprefixed word such as
	// "approve" or "lgtm" on a line of its own.
	DisableBareCommands bool `json:"disable_bare_commands"`

	// DisableUnapprove withdraws the unapprove and disapprove commands.
	DisableUnapprove bool `json:"disable_unapprove"`

	// DisableReactions stops a reaction on the pull request body counting as a
	// command at all.
	DisableReactions bool `json:"disable_reactions"`

	// DisableDeletedComments stops Smyklot reporting that a comment carrying a
	// command was deleted.
	DisableDeletedComments bool `json:"disable_deleted_comments"`

	// AllowSelfApproval lets the author of a pull request approve it. Off by
	// default: an approval is meant to be a second pair of eyes.
	AllowSelfApproval bool `json:"allow_self_approval"`

	// Runner names the entry point that acts on this repository, so the other
	// one stands down. It is settable only in the repository's own file: the
	// panel cannot write it, because a repository that has moved back to the
	// Action must be able to say so itself.
	Runner Runner `json:"runner"`
}

// Where the schema for this configuration is, spelled by the generator that
// wrote both it and this file.
//
// Generated rather than written twice, because three things have to agree: the
// document's own $id, the path the service answers at, and the directive the
// migration writes into a repository. A schema advertising an address nothing
// serves is the rot this generator exists to prevent.
const (
	// SchemaName is the schema document's file name.
	SchemaName = "repository-v1.json"

	// SchemaPath is where the service serves it, at the root of its origin
	// rather than under the panel: a schema is published documentation, and it
	// is served whether or not a deployment runs a panel at all.
	SchemaPath = "/schema/repository-v1.json"

	// SchemaURL is the published address, and what an editor is pointed at.
	SchemaURL = "https://smyklot.com/schema/repository-v1.json"
)

// The key every setting is addressed by, in a file, an environment variable,
// a command-line flag and the schema alike.
const (
	// KeyQuietSuccess addresses quiet_success.
	KeyQuietSuccess = "quiet_success"

	// KeyQuietReactions addresses quiet_reactions.
	KeyQuietReactions = "quiet_reactions"

	// KeyQuietPending addresses quiet_pending.
	KeyQuietPending = "quiet_pending"

	// KeyAllowedCommands addresses allowed_commands.
	KeyAllowedCommands = "allowed_commands"

	// KeyCommandAliases addresses command_aliases.
	KeyCommandAliases = "command_aliases"

	// KeyCommandPrefix addresses command_prefix.
	KeyCommandPrefix = "command_prefix"

	// KeyDisableMentions addresses disable_mentions.
	KeyDisableMentions = "disable_mentions"

	// KeyDisableBareCommands addresses disable_bare_commands.
	KeyDisableBareCommands = "disable_bare_commands"

	// KeyDisableUnapprove addresses disable_unapprove.
	KeyDisableUnapprove = "disable_unapprove"

	// KeyDisableReactions addresses disable_reactions.
	KeyDisableReactions = "disable_reactions"

	// KeyDisableDeletedComments addresses disable_deleted_comments.
	KeyDisableDeletedComments = "disable_deleted_comments"

	// KeyAllowSelfApproval addresses allow_self_approval.
	KeyAllowSelfApproval = "allow_self_approval"

	// KeyRunner addresses runner.
	KeyRunner = "runner"
)

// Default returns the configuration Smyklot runs with when nothing says
// otherwise. It is a fresh value every call: the slice and map fields are
// mutable, and a shared default would let one repository's resolution edit
// another's.
func Default() *Config {
	return &Config{
		QuietSuccess:           false,
		QuietReactions:         false,
		QuietPending:           false,
		AllowedCommands:        []string{},
		CommandAliases:         make(map[string]string),
		CommandPrefix:          "/",
		DisableMentions:        false,
		DisableBareCommands:    false,
		DisableUnapprove:       false,
		DisableReactions:       false,
		DisableDeletedComments: false,
		AllowSelfApproval:      false,
		Runner:                 "service",
	}
}

// Keys returns every configuration key, in declaration order.
func Keys() []string {
	return []string{
		KeyQuietSuccess,
		KeyQuietReactions,
		KeyQuietPending,
		KeyAllowedCommands,
		KeyCommandAliases,
		KeyCommandPrefix,
		KeyDisableMentions,
		KeyDisableBareCommands,
		KeyDisableUnapprove,
		KeyDisableReactions,
		KeyDisableDeletedComments,
		KeyAllowSelfApproval,
		KeyRunner,
	}
}

// PanelDeniedKeys returns the settings the panel must refuse to write.
//
// A setting lands here by carrying `panel:"deny"` on Patch, so the rule
// lives beside the field it governs rather than in a second package that has to
// remember to keep up.
func PanelDeniedKeys() []string {
	return []string{
		KeyRunner,
	}
}

// AsPatch returns this configuration as a layer that sets every setting.
//
// The list and the mapping are copied rather than pointed at, so the patch does
// not alias the configuration it came from. A caller holding both would
// otherwise find that editing one edited the other.
func (c Config) AsPatch() Patch {
	allowedCommands := append([]string{}, c.AllowedCommands...)
	commandAliases := maps.Clone(c.CommandAliases)

	return Patch{
		QuietSuccess:           &c.QuietSuccess,
		QuietReactions:         &c.QuietReactions,
		QuietPending:           &c.QuietPending,
		AllowedCommands:        &allowedCommands,
		CommandAliases:         &commandAliases,
		CommandPrefix:          &c.CommandPrefix,
		DisableMentions:        &c.DisableMentions,
		DisableBareCommands:    &c.DisableBareCommands,
		DisableUnapprove:       &c.DisableUnapprove,
		DisableReactions:       &c.DisableReactions,
		DisableDeletedComments: &c.DisableDeletedComments,
		AllowSelfApproval:      &c.AllowSelfApproval,
		Runner:                 &c.Runner,
	}
}

// SetKeys returns the keys this patch sets, in declaration order.
//
// A patch is sparse, so "which settings does this layer speak to" is a question
// only the pointers can answer. Counting or enumerating them by hand is how a
// key comes to be left out of one caller and not another.
func (p Patch) SetKeys() []string {
	keys := make([]string, 0, 13)

	if p.QuietSuccess != nil {
		keys = append(keys, KeyQuietSuccess)
	}

	if p.QuietReactions != nil {
		keys = append(keys, KeyQuietReactions)
	}

	if p.QuietPending != nil {
		keys = append(keys, KeyQuietPending)
	}

	if p.AllowedCommands != nil {
		keys = append(keys, KeyAllowedCommands)
	}

	if p.CommandAliases != nil {
		keys = append(keys, KeyCommandAliases)
	}

	if p.CommandPrefix != nil {
		keys = append(keys, KeyCommandPrefix)
	}

	if p.DisableMentions != nil {
		keys = append(keys, KeyDisableMentions)
	}

	if p.DisableBareCommands != nil {
		keys = append(keys, KeyDisableBareCommands)
	}

	if p.DisableUnapprove != nil {
		keys = append(keys, KeyDisableUnapprove)
	}

	if p.DisableReactions != nil {
		keys = append(keys, KeyDisableReactions)
	}

	if p.DisableDeletedComments != nil {
		keys = append(keys, KeyDisableDeletedComments)
	}

	if p.AllowSelfApproval != nil {
		keys = append(keys, KeyAllowSelfApproval)
	}

	if p.Runner != nil {
		keys = append(keys, KeyRunner)
	}

	return keys
}

// RegisterFlags defines a command-line flag for every setting that takes one,
// and --config-file, which names a document of them.
//
// A setting opts out with `flag:"-"` on Patch. The runner does, because it
// says which entry point acts on a repository and only the repository may
// answer that - a flag on the process would let one installation's deployment
// decide it for every repository it serves.
//
// This was written by hand and had fallen behind: quiet_pending had no flag at
// all, and nothing said so.
func RegisterFlags(flags *pflag.FlagSet) {
	defaults := Default()
	flags.Bool(KeyQuietSuccess, defaults.QuietSuccess, "Drops the comment a successful command would post, leaving only its reaction. Errors and warnings still comment.")
	flags.Bool(KeyQuietReactions, defaults.QuietReactions, "Drops the comment an approval or merge driven by a reaction would post.")
	flags.Bool(KeyQuietPending, defaults.QuietPending, "Drops the comment announcing that a merge is waiting on CI, leaving only its reaction.")
	flags.StringSlice(KeyAllowedCommands, defaults.AllowedCommands, "Narrows what may be run. An empty list allows every command; naming any command forbids the rest.")
	flags.StringToString(KeyCommandAliases, defaults.CommandAliases, "Maps a spelling somebody uses onto the command it means, such as \"app\" onto \"approve\".")
	flags.String(KeyCommandPrefix, defaults.CommandPrefix, "Opens a slash-style command, as \"/\" does in \"/approve\".")
	flags.Bool(KeyDisableMentions, defaults.DisableMentions, "Stops Smyklot answering a mention, such as \"@smyklot approve\".")
	flags.Bool(KeyDisableBareCommands, defaults.DisableBareCommands, "Stops Smyklot answering an unprefixed word such as \"approve\" or \"lgtm\" on a line of its own.")
	flags.Bool(KeyDisableUnapprove, defaults.DisableUnapprove, "Withdraws the unapprove and disapprove commands.")
	flags.Bool(KeyDisableReactions, defaults.DisableReactions, "Stops a reaction on the pull request body counting as a command at all.")
	flags.Bool(KeyDisableDeletedComments, defaults.DisableDeletedComments, "Stops Smyklot reporting that a comment carrying a command was deleted.")
	flags.Bool(KeyAllowSelfApproval, defaults.AllowSelfApproval, "Lets the author of a pull request approve it. Off by default: an approval is meant to be a second pair of eyes.")

	registerConfigFileFlag(flags)
}

// normalize turns whatever a decoder or a variable produced into a value this
// package vouches for.
//
// A setting whose Go type this package declares is only text until its own
// parser has seen it, and every layer reads text: a file, a document, a
// variable, a flag. Running this once in the resolver is what stops a typo
// being caught in a repository's file and waved through in an environment
// variable. The pointer is replaced rather than written through, since a patch
// may point into a Config that nothing asked to have edited.
func (p *Patch) normalize() error {
	if p.Runner != nil {
		value, err := ParseRunner(string(*p.Runner))
		if err != nil {
			return err
		}

		p.Runner = &value
	}

	return nil
}

// envPatch reads the layer written one variable per setting.
//
// A variable set to nothing counts as unset. A workflow that forwards an input
// nobody filled in writes an empty string, and reading that as an instruction
// would let a missing input narrow allowed_commands to nothing - on the layer
// stack that is fail-closed, so every command would be refused. viper read it
// the same way, for the same reason.
func envPatch(lookup func(string) (string, bool)) (Patch, error) {
	var patch Patch

	if raw, ok := lookup(EnvVar(KeyQuietSuccess)); ok && raw != "" {
		value, err := parseBool(KeyQuietSuccess, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.QuietSuccess = &value
	}

	if raw, ok := lookup(EnvVar(KeyQuietReactions)); ok && raw != "" {
		value, err := parseBool(KeyQuietReactions, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.QuietReactions = &value
	}

	if raw, ok := lookup(EnvVar(KeyQuietPending)); ok && raw != "" {
		value, err := parseBool(KeyQuietPending, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.QuietPending = &value
	}

	if raw, ok := lookup(EnvVar(KeyAllowedCommands)); ok && raw != "" {
		value := parseList(raw)
		patch.AllowedCommands = &value
	}

	if raw, ok := lookup(EnvVar(KeyCommandAliases)); ok && raw != "" {
		value, err := parseMapping(KeyCommandAliases, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.CommandAliases = &value
	}

	if raw, ok := lookup(EnvVar(KeyCommandPrefix)); ok && raw != "" {
		value := raw
		patch.CommandPrefix = &value
	}

	if raw, ok := lookup(EnvVar(KeyDisableMentions)); ok && raw != "" {
		value, err := parseBool(KeyDisableMentions, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.DisableMentions = &value
	}

	if raw, ok := lookup(EnvVar(KeyDisableBareCommands)); ok && raw != "" {
		value, err := parseBool(KeyDisableBareCommands, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.DisableBareCommands = &value
	}

	if raw, ok := lookup(EnvVar(KeyDisableUnapprove)); ok && raw != "" {
		value, err := parseBool(KeyDisableUnapprove, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.DisableUnapprove = &value
	}

	if raw, ok := lookup(EnvVar(KeyDisableReactions)); ok && raw != "" {
		value, err := parseBool(KeyDisableReactions, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.DisableReactions = &value
	}

	if raw, ok := lookup(EnvVar(KeyDisableDeletedComments)); ok && raw != "" {
		value, err := parseBool(KeyDisableDeletedComments, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.DisableDeletedComments = &value
	}

	if raw, ok := lookup(EnvVar(KeyAllowSelfApproval)); ok && raw != "" {
		value, err := parseBool(KeyAllowSelfApproval, raw)
		if err != nil {
			return Patch{}, err
		}

		patch.AllowSelfApproval = &value
	}

	if raw, ok := lookup(EnvVar(KeyRunner)); ok && raw != "" {
		value := Runner(raw)
		patch.Runner = &value
	}

	return patch, nil
}

// flagPatch reads the layer given on the command line.
//
// Changed is what makes this a patch rather than a whole configuration: a flag
// carries its default whether or not anyone passed it, and applying those
// defaults over the layers below would let the command line silently outrank a
// file it never mentioned. A flag no command registered reports false, so an
// entry point that takes fewer of them needs no special case.
func flagPatch(flags *pflag.FlagSet) (Patch, error) {
	var patch Patch

	if flags == nil {
		return patch, nil
	}

	if flags.Changed(KeyQuietSuccess) {
		value, err := flags.GetBool(KeyQuietSuccess)
		if err != nil {
			return Patch{}, err
		}

		patch.QuietSuccess = &value
	}

	if flags.Changed(KeyQuietReactions) {
		value, err := flags.GetBool(KeyQuietReactions)
		if err != nil {
			return Patch{}, err
		}

		patch.QuietReactions = &value
	}

	if flags.Changed(KeyQuietPending) {
		value, err := flags.GetBool(KeyQuietPending)
		if err != nil {
			return Patch{}, err
		}

		patch.QuietPending = &value
	}

	if flags.Changed(KeyAllowedCommands) {
		value, err := flags.GetStringSlice(KeyAllowedCommands)
		if err != nil {
			return Patch{}, err
		}

		patch.AllowedCommands = &value
	}

	if flags.Changed(KeyCommandAliases) {
		value, err := flags.GetStringToString(KeyCommandAliases)
		if err != nil {
			return Patch{}, err
		}

		patch.CommandAliases = &value
	}

	if flags.Changed(KeyCommandPrefix) {
		value, err := flags.GetString(KeyCommandPrefix)
		if err != nil {
			return Patch{}, err
		}

		patch.CommandPrefix = &value
	}

	if flags.Changed(KeyDisableMentions) {
		value, err := flags.GetBool(KeyDisableMentions)
		if err != nil {
			return Patch{}, err
		}

		patch.DisableMentions = &value
	}

	if flags.Changed(KeyDisableBareCommands) {
		value, err := flags.GetBool(KeyDisableBareCommands)
		if err != nil {
			return Patch{}, err
		}

		patch.DisableBareCommands = &value
	}

	if flags.Changed(KeyDisableUnapprove) {
		value, err := flags.GetBool(KeyDisableUnapprove)
		if err != nil {
			return Patch{}, err
		}

		patch.DisableUnapprove = &value
	}

	if flags.Changed(KeyDisableReactions) {
		value, err := flags.GetBool(KeyDisableReactions)
		if err != nil {
			return Patch{}, err
		}

		patch.DisableReactions = &value
	}

	if flags.Changed(KeyDisableDeletedComments) {
		value, err := flags.GetBool(KeyDisableDeletedComments)
		if err != nil {
			return Patch{}, err
		}

		patch.DisableDeletedComments = &value
	}

	if flags.Changed(KeyAllowSelfApproval) {
		value, err := flags.GetBool(KeyAllowSelfApproval)
		if err != nil {
			return Patch{}, err
		}

		patch.AllowSelfApproval = &value
	}

	return patch, nil
}

func applyPatch(values *Config, patch Patch, sources map[string]Source, source Source) {
	set(&values.QuietSuccess, patch.QuietSuccess, sources, KeyQuietSuccess, source)
	set(&values.QuietReactions, patch.QuietReactions, sources, KeyQuietReactions, source)
	set(&values.QuietPending, patch.QuietPending, sources, KeyQuietPending, source)
	setSlice(&values.AllowedCommands, patch.AllowedCommands, sources, KeyAllowedCommands, source)
	setMap(&values.CommandAliases, patch.CommandAliases, sources, KeyCommandAliases, source)
	set(&values.CommandPrefix, patch.CommandPrefix, sources, KeyCommandPrefix, source)
	set(&values.DisableMentions, patch.DisableMentions, sources, KeyDisableMentions, source)
	set(&values.DisableBareCommands, patch.DisableBareCommands, sources, KeyDisableBareCommands, source)
	set(&values.DisableUnapprove, patch.DisableUnapprove, sources, KeyDisableUnapprove, source)
	set(&values.DisableReactions, patch.DisableReactions, sources, KeyDisableReactions, source)
	set(&values.DisableDeletedComments, patch.DisableDeletedComments, sources, KeyDisableDeletedComments, source)
	set(&values.AllowSelfApproval, patch.AllowSelfApproval, sources, KeyAllowSelfApproval, source)
	set(&values.Runner, patch.Runner, sources, KeyRunner, source)
}

func processSources() map[string]Source {
	return map[string]Source{
		KeyQuietSuccess:           SourceProcess,
		KeyQuietReactions:         SourceProcess,
		KeyQuietPending:           SourceProcess,
		KeyAllowedCommands:        SourceProcess,
		KeyCommandAliases:         SourceProcess,
		KeyCommandPrefix:          SourceProcess,
		KeyDisableMentions:        SourceProcess,
		KeyDisableBareCommands:    SourceProcess,
		KeyDisableUnapprove:       SourceProcess,
		KeyDisableReactions:       SourceProcess,
		KeyDisableDeletedComments: SourceProcess,
		KeyAllowSelfApproval:      SourceProcess,
		KeyRunner:                 SourceProcess,
	}
}
