package configgen

import (
	"bytes"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"unicode/utf8"
)

const (
	// FrontendFormattingFile is the panel's generated formatting contract.
	FrontendFormattingFile = "internal/panel/frontend/src/lib/formatting.generated.ts"

	frontendHeader = "// Code generated by internal/configgen. DO NOT EDIT."
)

var (
	errFormattingMissing = errors.New("formatting object is missing")
	errFormattingShape   = errors.New("unsupported formatting model shape")
)

// RenderFrontendFormatting writes the TypeScript contract consumed by the
// panel. Patch remains the only hand-written configuration description: this
// output carries its nested policy shape, sparse patch type, preset policies,
// enum choices, integer bounds and documentation.
func RenderFrontendFormatting(model Model) ([]byte, error) {
	formatting, err := formattingField(model)
	if err != nil {
		return nil, err
	}
	presets, err := formattingPresets(formatting)
	if err != nil {
		return nil, err
	}

	var output bytes.Buffer
	output.WriteString(frontendHeader)
	output.WriteString("\n\nexport type FormattingPolicy = ")
	if err := writeTypeObject(&output, formatting.Children, 0); err != nil {
		return nil, err
	}
	output.WriteString(";\n\ntype SparseFormatting<Value> = {\n")
	output.WriteString("  [Key in keyof Value]?: Value[Key] extends object\n")
	output.WriteString("    ? SparseFormatting<Value[Key]>\n")
	output.WriteString("    : Value[Key];\n")
	output.WriteString("};\n\n")
	output.WriteString("export type FormattingPatch = SparseFormatting<FormattingPolicy>;\n\n")
	output.WriteString("type FormattingSourceTree<Value, Source extends string> = {\n")
	output.WriteString("  [Key in keyof Value]: Value[Key] extends object\n")
	output.WriteString("    ? FormattingSourceTree<Value[Key], Source>\n")
	output.WriteString("    : Source;\n")
	output.WriteString("};\n\n")
	output.WriteString("export type FormattingSources<Source extends string> = FormattingSourceTree<\n")
	output.WriteString("  FormattingPolicy,\n")
	output.WriteString("  Source\n")
	output.WriteString(">;\n\n")
	output.WriteString("export type FormattingPreset = FormattingPolicy['preset'];\n\n")
	output.WriteString("export const FORMATTING_PRESETS = {\n")
	for _, preset := range presets {
		fmt.Fprintf(&output, "  %s: ", quoteTypeScript(preset))
		if err := writeValueObject(&output, formatting.Children, preset, 1); err != nil {
			return nil, err
		}
		output.WriteString(",\n")
	}
	output.WriteString("} as const satisfies Record<FormattingPreset, FormattingPolicy>;\n\n")
	output.WriteString("export const FORMATTING_GROUPS = [\n")
	for _, field := range formatting.Children {
		if field.Kind != KindObject {
			continue
		}
		fmt.Fprintf(&output, "  { key: %s, label: %s, description: %s },\n",
			quoteTypeScript(typeScriptLocalKey(field.Key)),
			quoteTypeScript(field.GoName),
			quoteTypeScript(field.Description),
		)
	}
	output.WriteString("] as const;\n\n")
	output.WriteString("export type FormattingGroup = (typeof FORMATTING_GROUPS)[number];\n\n")
	output.WriteString("export const FORMATTING_FIELDS = [\n")
	for _, field := range flattenLeaves(formatting.Children) {
		if err := writeFieldDefinition(&output, field); err != nil {
			return nil, err
		}
	}
	output.WriteString("] as const;\n\n")
	output.WriteString("export type FormattingField = (typeof FORMATTING_FIELDS)[number];\n")
	output.WriteString("export type FormattingFieldKey = FormattingField['key'];\n")

	return output.Bytes(), nil
}

func formattingField(model Model) (Field, error) {
	for _, field := range model.Fields {
		if field.Key == "formatting" && field.Kind == KindObject {
			return field, nil
		}
	}

	return Field{}, errFormattingMissing
}

func formattingPresets(formatting Field) ([]string, error) {
	for _, field := range formatting.Children {
		if field.Key != "formatting.preset" {
			continue
		}
		if field.Kind != KindEnum || len(field.Enum) == 0 {
			return nil, fmt.Errorf("%w: formatting.preset must be a non-empty enum", errFormattingShape)
		}

		known := make(map[string]struct{}, len(field.Enum))
		for _, preset := range field.Enum {
			known[preset] = struct{}{}
		}
		for _, leaf := range flattenLeaves(formatting.Children) {
			for _, override := range leaf.Presets {
				if _, ok := known[override.Name]; !ok {
					return nil, fmt.Errorf(
						"%w: %s names unknown preset %q",
						errFormattingShape,
						leaf.Key,
						override.Name,
					)
				}
			}
		}

		return field.Enum, nil
	}

	return nil, fmt.Errorf("%w: formatting.preset is missing", errFormattingShape)
}

func writeTypeObject(output *bytes.Buffer, fields []Field, depth int) error {
	output.WriteString("{\n")
	for _, field := range fields {
		writeIndent(output, depth+1)
		output.WriteString(quoteTypeScript(typeScriptLocalKey(field.Key)))
		output.WriteString(": ")
		if field.Kind == KindObject {
			if err := writeTypeObject(output, field.Children, depth+1); err != nil {
				return err
			}
		} else {
			typeName, err := typeScriptType(field)
			if err != nil {
				return err
			}
			output.WriteString(typeName)
		}
		output.WriteString(";\n")
	}
	writeIndent(output, depth)
	output.WriteString("}")

	return nil
}

func typeScriptType(field Field) (string, error) {
	switch field.Kind {
	case KindInt:
		return "number", nil
	case KindEnum:
		choices := make([]string, 0, len(field.Enum))
		for _, choice := range field.Enum {
			choices = append(choices, quoteTypeScript(choice))
		}

		return strings.Join(choices, " | "), nil
	default:
		return "", fmt.Errorf("%w: %s has kind %s", errFormattingShape, field.Key, field.Kind)
	}
}

func writeValueObject(output *bytes.Buffer, fields []Field, preset string, depth int) error {
	output.WriteString("{\n")
	for _, field := range fields {
		writeIndent(output, depth+1)
		output.WriteString(quoteTypeScript(typeScriptLocalKey(field.Key)))
		output.WriteString(": ")
		if field.Kind == KindObject {
			if err := writeValueObject(output, field.Children, preset, depth+1); err != nil {
				return err
			}
		} else {
			value := field.Default
			for _, override := range field.Presets {
				if override.Name == preset {
					value = override.Value
					break
				}
			}
			rendered, err := typeScriptValue(field, value)
			if err != nil {
				return err
			}
			output.WriteString(rendered)
		}
		output.WriteString(",\n")
	}
	writeIndent(output, depth)
	output.WriteString("}")

	return nil
}

func typeScriptValue(field Field, raw string) (string, error) {
	if field.Kind != KindInt {
		return quoteTypeScript(raw), nil
	}
	if _, err := strconv.Atoi(raw); err != nil {
		return "", fmt.Errorf("%w: %s has non-integer value %q", errFormattingShape, field.Key, raw)
	}

	return raw, nil
}

func writeFieldDefinition(output *bytes.Buffer, field Field) error {
	path := strings.Split(strings.TrimPrefix(field.Key, "formatting."), ".")
	if len(path) == 0 || path[0] == field.Key {
		return fmt.Errorf("%w: %s is not below formatting", errFormattingShape, field.Key)
	}

	output.WriteString("  {\n")
	fmt.Fprintf(output, "    key: %s,\n", quoteTypeScript(field.Key))
	output.WriteString("    path: [")
	for index, part := range path {
		if index > 0 {
			output.WriteString(", ")
		}
		output.WriteString(quoteTypeScript(part))
	}
	output.WriteString("],\n")
	fmt.Fprintf(output, "    kind: %s,\n", quoteTypeScript(string(field.Kind)))
	value, err := typeScriptValue(field, field.Default)
	if err != nil {
		return err
	}
	fmt.Fprintf(output, "    defaultValue: %s,\n", value)
	if field.Kind == KindEnum {
		output.WriteString("    options: [")
		for index, option := range field.Enum {
			if index > 0 {
				output.WriteString(", ")
			}
			output.WriteString(quoteTypeScript(option))
		}
		output.WriteString("],\n")
	}
	if field.Kind == KindInt {
		fmt.Fprintf(output, "    minimum: %s,\n", field.Min)
		fmt.Fprintf(output, "    maximum: %s,\n", field.Max)
	}
	fmt.Fprintf(output, "    description: %s,\n", quoteTypeScript(field.Description))
	output.WriteString("  },\n")

	return nil
}

func typeScriptLocalKey(key string) string {
	if index := strings.LastIndexByte(key, '.'); index >= 0 {
		return key[index+1:]
	}

	return key
}

func writeIndent(output *bytes.Buffer, depth int) {
	output.WriteString(strings.Repeat("  ", depth))
}

func quoteTypeScript(value string) string {
	var output strings.Builder
	output.Grow(len(value) + 2)
	output.WriteByte('\'')

	for len(value) > 0 {
		r, size := utf8.DecodeRuneInString(value)
		value = value[size:]

		switch r {
		case '\'':
			output.WriteString("\\'")
		case '\\':
			output.WriteString("\\\\")
		case '\n':
			output.WriteString("\\n")
		case '\r':
			output.WriteString("\\r")
		case '\t':
			output.WriteString("\\t")
		case '\u2028', '\u2029':
			fmt.Fprintf(&output, "\\u%04x", r)
		default:
			if r < 0x20 {
				fmt.Fprintf(&output, "\\u%04x", r)
				continue
			}
			output.WriteRune(r)
		}
	}

	output.WriteByte('\'')

	return output.String()
}
