package configgen

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"
	"text/template"
	"unicode"
)

const (
	// PackageDir is the package Parse reads, relative to the repository root.
	PackageDir = "pkg/config"

	// GoFile is where RenderGo's output belongs, relative to the repository root.
	GoFile = "pkg/config/zz_generated.go"
)

// goHeader is the line that makes every tool in the repository treat the file
// as generated: golangci-lint's `generated: strict` mode, gopls, and anyone
// reading it. The wording is fixed by convention, not by taste.
const goHeader = "// Code generated by internal/configgen. DO NOT EDIT."

// docWidth is where a generated comment wraps, chosen so a field's comment sits
// inside 80 columns once the tab and the "// " are counted.
const docWidth = 72

var goTemplate = template.Must(template.New("go").Funcs(template.FuncMap{
	"zero":        zeroValue,
	"applier":     applier,
	"quote":       strconv.Quote,
	"comment":     comment,
	"local":       localName,
	"needsCopy":   needsCopy,
	"copyExpr":    copyExpr,
	"patchRef":    patchRef,
	"flagMethod":  flagMethod,
	"envRead":     envRead,
	"flagRead":    flagRead,
	"object":      isObject,
	"valueAccess": valueAccess,
	"setKeys":     setKeysBlock,
	"normalize":   normalizeBlock,
	"patchSet":    patchSet,
	"applyLine":   applyLine,
}).Parse(`{{ .Header }}

package config
{{ if or .Std .ThirdParty }}
import (
{{- range .Std }}
	{{ quote . }}
{{- end }}
{{- if and .Std .ThirdParty }}
{{ end }}
{{- range .ThirdParty }}
	{{ quote . }}
{{- end }}
)
{{ end }}

// Config is the effective configuration: every setting resolved to one value.
//
// It is the shape the rest of Smyklot reads. Patch is the shape a layer is
// written in, and this is what a stack of layers collapses to.
type Config struct {
{{- range .Fields }}
{{ comment .Doc }}
	{{ .GoName }} {{ .GoType }} ` + "`json:{{ quote .Key }}`" + `
{{ end -}}
}

// Where the schema for this configuration is, spelled by the generator that
// wrote both it and this file.
//
// Generated rather than written twice, because three things have to agree: the
// document's own $id, the path the service answers at, and the directive the
// migration writes into a repository. A schema advertising an address nothing
// serves is the rot this generator exists to prevent.
const (
	// SchemaName is the schema document's file name.
	SchemaName = {{ quote .SchemaName }}

	// SchemaPath is where the service serves it, at the root of its origin
	// rather than under the panel: a schema is published documentation, and it
	// is served whether or not a deployment runs a panel at all.
	SchemaPath = {{ quote .SchemaPath }}

	// SchemaURL is the published address, and what an editor is pointed at.
	SchemaURL = {{ quote .SchemaID }}
)

// The key every setting is addressed by, in a file, an environment variable,
// a command-line flag and the schema alike.
const (
	{{- range .Leaves }}
	// Key{{ .ConstName }} addresses {{ .Key }}.
	Key{{ .ConstName }} = {{ quote .Key }}
{{ end -}}
)

// Default returns the configuration Smyklot runs with when nothing says
// otherwise. It is a fresh value every call: the slice and map fields are
// mutable, and a shared default would let one repository's resolution edit
// another's.
func Default() *Config {
	return &Config{
{{- range .Fields }}
		{{ .GoName }}: {{ zero . }},
{{- end }}
	}
}

// Keys returns every configuration key, in declaration order.
func Keys() []string {
	return []string{
	{{- range .Leaves }}
		Key{{ .ConstName }},
{{- end }}
	}
}

// PanelDeniedKeys returns the settings the panel must refuse to write.
//
// A setting lands here by carrying ` + "`panel:\"deny\"`" + ` on Patch, so the rule
// lives beside the field it governs rather than in a second package that has to
// remember to keep up.
func PanelDeniedKeys() []string {
	return []string{
	{{- range .Leaves }}{{ if .PanelDeny }}
		Key{{ .ConstName }},
{{- end }}{{ end }}
	}
}

// AsPatch returns this configuration as a layer that sets every setting.
//
// The list and the mapping are copied rather than pointed at, so the patch does
// not alias the configuration it came from. A caller holding both would
// otherwise find that editing one edited the other.
func (c Config) AsPatch() Patch {
{{- range .Fields }}{{ if object . }}
	{{ local .GoName }} := c.{{ .GoName }}.AsPatch()
{{- else }}{{ if needsCopy . }}
	{{ local .GoName }} := {{ copyExpr . }}
{{- end }}{{ end }}{{ end }}

	return Patch{
{{- range .Fields }}
		{{ .GoName }}: {{ patchRef . }},
{{- end }}
	}
}

// SetKeys returns the keys this patch sets, in declaration order.
//
// A patch is sparse, so "which settings does this layer speak to" is a question
// only the pointers can answer. Counting or enumerating them by hand is how a
// key comes to be left out of one caller and not another.
func (p Patch) SetKeys() []string {
	keys := make([]string, 0, {{ len .Leaves }})

{{ range .Fields }}{{ setKeys . }}
{{ end }}	return keys
}

// RegisterFlags defines a command-line flag for every setting that takes one,
// and --config-file, which names a document of them.
//
// A setting opts out with ` + "`flag:\"-\"`" + ` on Patch. The runner does, because it
// says which entry point acts on a repository and only the repository may
// answer that - a flag on the process would let one installation's deployment
// decide it for every repository it serves.
//
// This was written by hand and had fallen behind: quiet_pending had no flag at
// all, and nothing said so.
func RegisterFlags(flags *pflag.FlagSet) {
	defaults := Default()
{{ range .Leaves }}{{ if .HasFlag }}	flags.{{ flagMethod . }}(FlagName(Key{{ .ConstName }}), {{ valueAccess "defaults" . }}, {{ quote .Description }})
{{ end }}{{ end }}
	registerConfigFileFlag(flags)
}

// normalize turns whatever a decoder or a variable produced into a value this
// package vouches for.
//
// A setting whose Go type this package declares is only text until its own
// parser has seen it, and every layer reads text: a file, a document, a
// variable, a flag. Running this once in the resolver is what stops a typo
// being caught in a repository's file and waved through in an environment
// variable. The pointer is replaced rather than written through, since a patch
// may point into a Config that nothing asked to have edited.
func (p *Patch) normalize() error {
{{- range .Fields }}
{{ normalize . }}
{{- end }}
	return nil
}

// envPatch reads the layer written one variable per setting.
//
// A variable set to nothing counts as unset. A workflow that forwards an input
// nobody filled in writes an empty string, and reading that as an instruction
// would let a missing input narrow allowed_commands to nothing - on the layer
// stack that is fail-closed, so every command would be refused. viper read it
// the same way, for the same reason.
func envPatch(lookup func(string) (string, bool)) (Patch, error) {
	var patch Patch
{{ range .Leaves }}
	if raw, ok := lookup(EnvVar(Key{{ .ConstName }})); ok && raw != "" {
		{{ envRead . }}
		{{ patchSet . "&value" }}
	}
{{ end }}
	return patch, nil
}

// flagPatch reads the layer given on the command line.
//
// Changed is what makes this a patch rather than a whole configuration: a flag
// carries its default whether or not anyone passed it, and applying those
// defaults over the layers below would let the command line silently outrank a
// file it never mentioned. A flag no command registered reports false, so an
// entry point that takes fewer of them needs no special case.
func flagPatch(flags *pflag.FlagSet) (Patch, error) {
	var patch Patch

	if flags == nil {
		return patch, nil
	}
{{ range .Leaves }}{{ if .HasFlag }}
	if flags.Changed(FlagName(Key{{ .ConstName }})) {
		value, err := flags.Get{{ flagMethod . }}(FlagName(Key{{ .ConstName }}))
		if err != nil {
			return Patch{}, err
		}

		{{ flagRead . }}
	}
{{ end }}{{ end }}
	return patch, nil
}

func applyPatch(values *Config, patch Patch, sources map[string]Source, source Source) {
{{- range .Fields }}
	{{ applyLine . }}
{{- end }}
}

func processSources() map[string]Source {
	return map[string]Source{
	{{- range .Leaves }}
		Key{{ .ConstName }}: SourceProcess,
{{- end }}
	}
}
`))

// RenderGo produces pkg/config/zz_generated.go.
//
// The bytes are run through go/format, which is the standard library rather
// than a tool with a version to pin, so the same model renders the same file on
// every machine. dotsync's generator round-tripped through a map and then left
// canonical ordering to a formatter that ran only in CI, and the phantom diff
// that produced is why its schema came to be hand-edited.
func RenderGo(model Model) ([]byte, error) {
	var buffer bytes.Buffer

	std, thirdParty := imports(model)

	data := struct {
		Header     string
		Std        []string
		ThirdParty []string
		Fields     []Field
		Leaves     []Field
		SchemaName string
		SchemaPath string
		SchemaID   string
	}{
		Header: goHeader, Std: std, ThirdParty: thirdParty,
		Fields: model.Fields, Leaves: model.Leaves,
		SchemaName: SchemaName, SchemaPath: SchemaPath, SchemaID: SchemaID,
	}

	if err := goTemplate.Execute(&buffer, data); err != nil {
		return nil, fmt.Errorf("render go: %w", err)
	}

	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated go: %w", err)
	}

	return formatted, nil
}

// zeroValue renders the Go expression for a field's default.
//
// A missing default tag means the type's zero value, which is what makes the
// tag optional for the eleven booleans that are all false.
func zeroValue(field Field) string {
	switch field.Kind {
	case KindObject:
		return "Default" + field.GoType + "()"

	case KindInt:
		return field.Default

	case KindStringSlice:
		return "[]string{}"

	case KindStringMap:
		return "make(map[string]string)"

	case KindBool:
		if field.Default == "" {
			return "false"
		}

		return field.Default

	default:
		return strconv.Quote(field.Default)
	}
}

// imports lists what the rendered file needs, split into the two groups gofmt
// separates with a blank line.
//
// pflag is unconditional because flagPatch takes a *pflag.FlagSet whether or
// not any setting has a flag - a process still reads the layer, it is just
// empty. maps is conditional on a map field, since an import emitted regardless
// would stop compiling the moment the last one was removed.
func imports(model Model) (std, thirdParty []string) {
	for _, field := range model.Leaves {
		if field.Kind == KindStringMap {
			std = append(std, "maps")

			break
		}
	}

	return std, []string{"github.com/spf13/pflag"}
}

// envRead renders the statements that turn one variable's text into a value.
//
// The lines are emitted with their own newlines rather than as one statement,
// because gofmt keeps a single-line if block on one line and the result would
// read unlike anything in the package.
func envRead(field Field) string {
	switch {
	case field.Kind == KindBool:
		return checked("parseBool(Key" + field.ConstName + ", raw)")

	case field.Kind == KindInt:
		return checked("parseInt(Key" + field.ConstName + ", raw)")

	case field.Kind == KindStringSlice:
		return "value := parseList(raw)"

	case field.Kind == KindStringMap:
		return checked("parseMapping(Key" + field.ConstName + ", raw)")

	case field.Named:
		return "value := " + field.GoType + "(raw)"

	default:
		return "value := raw"
	}
}

// flagRead renders what flagPatch does with the value pflag handed back.
//
// A named string type needs converting, since pflag only knows the builtin it
// was registered as.
func flagRead(field Field) string {
	if !field.Named {
		return patchSet(field, "&value")
	}

	local := localName(field.GoName)

	return local + " := " + field.GoType + "(value)\n" +
		patchSet(field, "&"+local)
}

// checked renders a call that can fail, with the error returned.
func checked(call string) string {
	return "value, err := " + call + "\n" +
		"if err != nil {\n" +
		"return Patch{}, err\n" +
		"}\n"
}

// flagMethod names the pflag registrar for a field's type.
func flagMethod(field Field) string {
	switch field.Kind {
	case KindBool:
		return "Bool"

	case KindStringSlice:
		return "StringSlice"

	case KindStringMap:
		return "StringToString"

	case KindInt:
		return "Int"

	default:
		return "String"
	}
}

// needsCopy reports a field that AsPatch has to copy rather than point at. A
// scalar lives in the method's own copy of the receiver, so its address is
// already private; a slice or a map carries a reference to the caller's memory.
func needsCopy(field Field) bool {
	return field.Kind == KindStringSlice || field.Kind == KindStringMap
}

// copyExpr renders the deep copy needsCopy calls for.
func copyExpr(field Field) string {
	if field.Kind == KindStringSlice {
		return "append([]string{}, c." + field.GoName + "...)"
	}

	return "maps.Clone(c." + field.GoName + ")"
}

// patchRef renders what AsPatch points the patch field at.
func patchRef(field Field) string {
	if isObject(field) {
		return "&" + localName(field.GoName)
	}

	if needsCopy(field) {
		return "&" + localName(field.GoName)
	}

	return "&c." + field.GoName
}

// localName renders a Go identifier for a field's local copy.
func localName(goName string) string {
	return mapFirstRune(goName, unicode.ToLower)
}

// applier names the helper that applies one field, which differs only because a
// slice and a map have to be copied rather than assigned.
func applier(field Field) string {
	switch field.Kind {
	case KindStringSlice:
		return "setSlice"

	case KindStringMap:
		return "setMap"

	default:
		return "set"
	}
}

func isObject(field Field) bool { return field.Kind == KindObject }

func valueAccess(root string, field Field) string {
	return root + "." + strings.Join(field.GoPath, ".")
}

func setKeysBlock(field Field) string {
	if isObject(field) {
		return "\tif p." + field.GoName + " != nil {\n" +
			"\t\tkeys = append(keys, p." + field.GoName + ".SetKeys()...)\n" +
			"\t}\n"
	}

	return "\tif p." + field.GoName + " != nil {\n" +
		"\t\tkeys = append(keys, Key" + field.ConstName + ")\n" +
		"\t}\n"
}

func normalizeBlock(field Field) string {
	if isObject(field) {
		return "\tif p." + field.GoName + " != nil {\n" +
			"\t\tif err := p." + field.GoName + ".normalize(); err != nil {\n" +
			"\t\t\treturn err\n\t\t}\n\t}\n"
	}

	if !field.Named {
		return ""
	}

	return "\tif p." + field.GoName + " != nil {\n" +
		"\t\tvalue, err := Parse" + field.GoType + "(string(*p." + field.GoName + "))\n" +
		"\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n" +
		"\t\tp." + field.GoName + " = &value\n\t}\n"
}

func patchSet(field Field, value string) string {
	var lines strings.Builder

	for depth := 1; depth < len(field.GoPath); depth++ {
		access := "patch." + strings.Join(field.GoPath[:depth], ".")
		typeName := strings.Join(field.GoPath[:depth], "") + "Patch"
		fmt.Fprintf(&lines, "if %s == nil { %s = &%s{} }\n", access, access, typeName)
	}

	lines.WriteString("patch.")
	lines.WriteString(strings.Join(field.GoPath, "."))
	lines.WriteString(" = ")
	lines.WriteString(value)

	return lines.String()
}

func applyLine(field Field) string {
	if isObject(field) {
		return "if patch." + field.GoName + " != nil { apply" + field.GoName +
			"Patch(&values." + field.GoName + ", *patch." + field.GoName +
			", sources, source) }"
	}

	return applier(field) + "(&values." + field.GoName + ", patch." + field.GoName +
		", sources, Key" + field.ConstName + ", source)"
}

// GoDoc reports the generated file's header, so a test can assert the marker is
// present without repeating the exact wording.
func GoDoc() string { return strings.TrimPrefix(goHeader, "// ") }

// comment renders a doc comment as tab-indented lines wrapped at docWidth.
//
// The model holds each comment as one long line, because that is the form the
// schema wants. Emitting it into Go that way would produce a file nobody would
// have written by hand, and a generated file that reads unlike its source is
// one people stop reading.
func comment(text string) string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return ""
	}

	lines := make([]string, 0, len(words))
	line := words[0]

	for _, word := range words[1:] {
		if len(line)+1+len(word) > docWidth {
			lines = append(lines, line)
			line = word

			continue
		}

		line += " " + word
	}

	lines = append(lines, line)

	for index, text := range lines {
		lines[index] = "\t// " + text
	}

	return strings.Join(lines, "\n")
}
