package configgen

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"
	"text/template"
	"unicode"
)

const (
	// PackageDir is the package Parse reads, relative to the repository root.
	PackageDir = "pkg/config"

	// GoFile is where RenderGo's output belongs, relative to the repository root.
	GoFile = "pkg/config/zz_generated.go"
)

// goHeader is the line that makes every tool in the repository treat the file
// as generated: golangci-lint's `generated: strict` mode, gopls, and anyone
// reading it. The wording is fixed by convention, not by taste.
const goHeader = "// Code generated by internal/configgen. DO NOT EDIT."

// docWidth is where a generated comment wraps, chosen so a field's comment sits
// inside 80 columns once the tab and the "// " are counted.
const docWidth = 72

var goTemplate = template.Must(template.New("go").Funcs(template.FuncMap{
	"zero":      zeroValue,
	"applier":   applier,
	"quote":     strconv.Quote,
	"comment":   comment,
	"local":     localName,
	"needsCopy": needsCopy,
	"copyExpr":  copyExpr,
	"patchRef":  patchRef,
}).Parse(`{{ .Header }}

package config
{{ if .Imports }}
import (
{{- range .Imports }}
	{{ quote . }}
{{- end }}
)
{{ end }}

// Config is the effective configuration: every setting resolved to one value.
//
// It is the shape the rest of Smyklot reads. Patch is the shape a layer is
// written in, and this is what a stack of layers collapses to.
type Config struct {
{{- range .Fields }}
{{ comment .Doc }}
	{{ .GoName }} {{ .GoType }} ` + "`json:{{ quote .Key }}`" + `
{{ end -}}
}

// The key every setting is addressed by, in a file, an environment variable,
// a command-line flag and the schema alike.
const (
{{- range .Fields }}
	// Key{{ .GoName }} addresses {{ .Key }}.
	Key{{ .GoName }} = {{ quote .Key }}
{{ end -}}
)

// Default returns the configuration Smyklot runs with when nothing says
// otherwise. It is a fresh value every call: the slice and map fields are
// mutable, and a shared default would let one repository's resolution edit
// another's.
func Default() *Config {
	return &Config{
{{- range .Fields }}
		{{ .GoName }}: {{ zero . }},
{{- end }}
	}
}

// Keys returns every configuration key, in declaration order.
func Keys() []string {
	return []string{
{{- range .Fields }}
		Key{{ .GoName }},
{{- end }}
	}
}

// PanelDeniedKeys returns the settings the panel must refuse to write.
//
// A setting lands here by carrying ` + "`panel:\"deny\"`" + ` on Patch, so the rule
// lives beside the field it governs rather than in a second package that has to
// remember to keep up.
func PanelDeniedKeys() []string {
	return []string{
{{- range .Fields }}{{ if .PanelDeny }}
		Key{{ .GoName }},
{{- end }}{{ end }}
	}
}

// AsPatch returns this configuration as a layer that sets every setting.
//
// The list and the mapping are copied rather than pointed at, so the patch does
// not alias the configuration it came from. A caller holding both would
// otherwise find that editing one edited the other.
func (c Config) AsPatch() Patch {
{{- range .Fields }}{{ if needsCopy . }}
	{{ local .GoName }} := {{ copyExpr . }}
{{- end }}{{ end }}

	return Patch{
{{- range .Fields }}
		{{ .GoName }}: {{ patchRef . }},
{{- end }}
	}
}

// SetKeys returns the keys this patch sets, in declaration order.
//
// A patch is sparse, so "which settings does this layer speak to" is a question
// only the pointers can answer. Counting or enumerating them by hand is how a
// key comes to be left out of one caller and not another.
func (p Patch) SetKeys() []string {
	keys := make([]string, 0, {{ len .Fields }})

{{ range .Fields }}	if p.{{ .GoName }} != nil {
		keys = append(keys, Key{{ .GoName }})
	}

{{ end }}	return keys
}

func applyPatch(values *Config, patch Patch, sources map[string]Source, source Source) {
{{- range .Fields }}
	{{ applier . }}(&values.{{ .GoName }}, patch.{{ .GoName }}, sources, Key{{ .GoName }}, source)
{{- end }}
}

func processSources() map[string]Source {
	return map[string]Source{
{{- range .Fields }}
		Key{{ .GoName }}: SourceProcess,
{{- end }}
	}
}
`))

// RenderGo produces pkg/config/zz_generated.go.
//
// The bytes are run through go/format, which is the standard library rather
// than a tool with a version to pin, so the same model renders the same file on
// every machine. dotsync's generator round-tripped through a map and then left
// canonical ordering to a formatter that ran only in CI, and the phantom diff
// that produced is why its schema came to be hand-edited.
func RenderGo(model Model) ([]byte, error) {
	var buffer bytes.Buffer

	data := struct {
		Header  string
		Imports []string
		Fields  []Field
	}{Header: goHeader, Imports: imports(model), Fields: model.Fields}

	if err := goTemplate.Execute(&buffer, data); err != nil {
		return nil, fmt.Errorf("render go: %w", err)
	}

	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated go: %w", err)
	}

	return formatted, nil
}

// zeroValue renders the Go expression for a field's default.
//
// A missing default tag means the type's zero value, which is what makes the
// tag optional for the eleven booleans that are all false.
func zeroValue(field Field) string {
	switch field.Kind {
	case KindStringSlice:
		return "[]string{}"

	case KindStringMap:
		return "make(map[string]string)"

	case KindBool:
		if field.Default == "" {
			return "false"
		}

		return field.Default

	default:
		return strconv.Quote(field.Default)
	}
}

// imports lists what the rendered file needs, which depends on the fields it
// holds. An import emitted unconditionally would not compile the moment the
// last map field was removed.
func imports(model Model) []string {
	for _, field := range model.Fields {
		if field.Kind == KindStringMap {
			return []string{"maps"}
		}
	}

	return nil
}

// needsCopy reports a field that AsPatch has to copy rather than point at. A
// scalar lives in the method's own copy of the receiver, so its address is
// already private; a slice or a map carries a reference to the caller's memory.
func needsCopy(field Field) bool {
	return field.Kind == KindStringSlice || field.Kind == KindStringMap
}

// copyExpr renders the deep copy needsCopy calls for.
func copyExpr(field Field) string {
	if field.Kind == KindStringSlice {
		return "append([]string{}, c." + field.GoName + "...)"
	}

	return "maps.Clone(c." + field.GoName + ")"
}

// patchRef renders what AsPatch points the patch field at.
func patchRef(field Field) string {
	if needsCopy(field) {
		return "&" + localName(field.GoName)
	}

	return "&c." + field.GoName
}

// localName renders a Go identifier for a field's local copy.
func localName(goName string) string {
	return mapFirstRune(goName, unicode.ToLower)
}

// applier names the helper that applies one field, which differs only because a
// slice and a map have to be copied rather than assigned.
func applier(field Field) string {
	switch field.Kind {
	case KindStringSlice:
		return "setSlice"

	case KindStringMap:
		return "setMap"

	default:
		return "set"
	}
}

// GoDoc reports the generated file's header, so a test can assert the marker is
// present without repeating the exact wording.
func GoDoc() string { return strings.TrimPrefix(goHeader, "// ") }

// comment renders a doc comment as tab-indented lines wrapped at docWidth.
//
// The model holds each comment as one long line, because that is the form the
// schema wants. Emitting it into Go that way would produce a file nobody would
// have written by hand, and a generated file that reads unlike its source is
// one people stop reading.
func comment(text string) string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return ""
	}

	lines := make([]string, 0, len(words))
	line := words[0]

	for _, word := range words[1:] {
		if len(line)+1+len(word) > docWidth {
			lines = append(lines, line)
			line = word

			continue
		}

		line += " " + word
	}

	lines = append(lines, line)

	for index, text := range lines {
		lines[index] = "\t// " + text
	}

	return strings.Join(lines, "\n")
}
