package configgen_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
	"testing"

	"github.com/smykla-skalski/smyklot/internal/configgen"
	"github.com/smykla-skalski/smyklot/internal/orgsync"
	"github.com/smykla-skalski/smyklot/pkg/config"
)

func TestPanelSchemasAreCurrentAndKeepLegacyContract(t *testing.T) {
	model := parse(t)
	first, err := configgen.RenderPanelSchemas(model)
	if err != nil {
		t.Fatal(err)
	}
	second, err := configgen.RenderPanelSchemas(model)
	if err != nil || !reflect.DeepEqual(first, second) {
		t.Fatalf("panel schema generation is not deterministic: %v", err)
	}
	for path, rendered := range first {
		stored, err := os.ReadFile(filepath.Join(repoRoot, path))
		if err != nil || string(stored) != string(rendered) {
			t.Fatalf("%s is stale - run mise run generate: %v", path, err)
		}
		embedded, ok := config.Schema(filepath.Base(path))
		if !ok || string(embedded) != string(rendered) {
			t.Fatalf("%s is not published with its generated bytes", path)
		}
	}
	legacy := readSchema(t)
	if _, changed := legacy.Properties["panel"]; changed {
		t.Fatal("panel settings changed the pinned legacy schema")
	}
	for _, scope := range []config.PanelFileScope{config.PanelFileRepository, config.PanelFileWorkspace} {
		document := readPanelSchema(t, scope)
		delete(document.Properties, "panel")
		expected := readSchema(t).Properties
		if scope == config.PanelFileWorkspace {
			delete(expected, "runner")
		}
		if !reflect.DeepEqual(document.Properties, expected) {
			t.Fatalf("%s schema changed command setting definitions", scope)
		}
	}
}

func TestPanelSchemasCoverTypedFieldsAtEachScope(t *testing.T) {
	for _, scope := range []config.PanelFileScope{config.PanelFileRepository, config.PanelFileWorkspace} {
		document := readPanelSchema(t, scope)
		section := document.Properties["panel"]
		assertPanelFields(t, section, reflect.TypeFor[config.PanelFileSection](), "")
		settings := section.Properties["settings"]
		omitted := "repository_default_enabled"
		if scope == config.PanelFileWorkspace {
			omitted = "enabled"
		}
		assertPanelFields(t, settings, reflect.TypeFor[config.PanelFileSettings](), omitted)
		assertPanelFields(t, settings.Properties["protected_refs"], reflect.TypeFor[config.PanelFileRefs](), "")
		exceptions := settings.Properties["merge_exceptions"]
		assertPanelFields(t, exceptions, reflect.TypeFor[config.PanelFileExceptions](), "")
		assertPanelFields(t, *exceptions.Properties["actors"].Items, reflect.TypeFor[config.PanelFileActor](), "")
		if !reflect.DeepEqual(section.Properties["scope"].Enum, []string{string(scope)}) {
			t.Fatalf("%s schema accepts a different panel scope", scope)
		}
		if section.Properties["version"].Minimum == nil || *section.Properties["version"].Minimum != 1 ||
			section.Properties["version"].Maximum == nil || *section.Properties["version"].Maximum != 1 {
			t.Fatalf("%s schema accepts an unsupported version", scope)
		}
		if scope == config.PanelFileWorkspace {
			if !slices.Contains(document.Required, "panel") || !slices.Contains(section.Required, "settings") ||
				!reflect.DeepEqual(settings.Required, []string{"repository_default_enabled", "merge_mode", "protected_refs"}) {
				t.Fatal("workspace schema permits omission of required defaults")
			}
		} else if len(document.Required) != 0 || len(settings.Required) != 0 {
			t.Fatal("repository schema lost sparse inheritance")
		}
	}
}

func TestPanelSchemasDescribeTheSyncWireValues(t *testing.T) {
	for _, scope := range []config.PanelFileScope{config.PanelFileRepository, config.PanelFileWorkspace} {
		sync := readPanelSchema(t, scope).Properties["panel"].Properties["sync"]
		if len(sync.Properties) != len(orgsync.Kinds()) || string(sync.AdditionalProperties) != "false" {
			t.Fatalf("%s schema has a different Sync kind set", scope)
		}
		for _, kind := range orgsync.Kinds() {
			item, exists := sync.Properties[string(kind)]
			if !exists {
				t.Fatalf("%s schema omits %s", scope, kind)
			}
			assertPanelFields(t, item, reflect.TypeFor[config.PanelFileSync](), "")
			document := item.Properties["document"]
			if document.Type != "string" || document.ContentMediaType != "application/json" ||
				!slices.Contains(item.Required, "document") {
				t.Fatalf("%s schema does not describe the multiline JSON string", kind)
			}
			if slices.Contains(item.Required, "enabled") != (scope == config.PanelFileWorkspace) {
				t.Fatalf("%s schema changed %s enabled inheritance", scope, kind)
			}
		}
	}
}

func TestPanelSchemaActorCompletionsAreImportable(t *testing.T) {
	actors := readPanelSchema(t, config.PanelFileRepository).Properties["panel"].Properties["settings"].
		Properties["merge_exceptions"].Properties["actors"].Items
	covered := make([]string, 0, len(actors.Properties["type"].Enum))
	for _, variant := range actors.OneOf {
		modes := variant.Properties["mode"].Enum
		if len(modes) == 0 {
			modes = actors.Properties["mode"].Enum
		}
		var id int64
		if minimum := variant.Properties["id"].Minimum; minimum != nil {
			id = int64(*minimum)
			if !slices.Contains(variant.Required, "id") {
				t.Fatal("schema omits required actor ID")
			}
		}
		for _, actorType := range variant.Properties["type"].Enum {
			covered = append(covered, actorType)
			for _, mode := range modes {
				actor := orgsync.RulesetBypassActor{ActorID: id, ActorType: actorType, Mode: mode}
				if err := orgsync.ValidateRulesetBypassActors([]orgsync.RulesetBypassActor{actor}); err != nil {
					t.Fatalf("schema offers unusable actor %s/%s: %v", actorType, mode, err)
				}
			}
		}
	}
	slices.Sort(covered)
	want := slices.Clone(actors.Properties["type"].Enum)
	slices.Sort(want)
	if !slices.Equal(covered, want) {
		t.Fatal("actor branches must cover every type exactly once")
	}
}

func readPanelSchema(t *testing.T, scope config.PanelFileScope) schemaDocument {
	t.Helper()
	name, url := configgen.RepositoryPanelSchemaName, config.RepositoryPanelSchemaURL
	if scope == config.PanelFileWorkspace {
		name, url = configgen.WorkspacePanelSchemaName, config.WorkspacePanelSchemaURL
	}
	content, ok := config.Schema(name)
	if !ok {
		t.Fatalf("%s is not embedded", name)
	}
	var document schemaDocument
	if err := json.Unmarshal(content, &document); err != nil {
		t.Fatal(err)
	}
	if document.ID != url || document.Schema != configgen.SchemaDialect || document.AdditionalProperties {
		t.Fatalf("incorrect public schema identity or unknown-field contract: %+v", document)
	}
	return document
}

func assertPanelFields(t *testing.T, property schemaProperty, source reflect.Type, omitted string) {
	t.Helper()
	expected := 0
	for index := range source.NumField() {
		field := source.Field(index)
		key := strings.Split(field.Tag.Get("json"), ",")[0]
		if key == omitted {
			if _, exists := property.Properties[key]; exists {
				t.Fatalf("%s schema exposes %s at the wrong scope", source, key)
			}
			continue
		}
		expected++
		if _, exists := property.Properties[key]; !exists {
			t.Fatalf("%s schema omits typed field %s", source, key)
		}
	}
	if property.Type != "object" || string(property.AdditionalProperties) != "false" || len(property.Properties) != expected {
		t.Fatalf("%s schema does not match the closed typed object", source)
	}
}
